### ISSUE TITLE
Dumped image from mi424wr rev D can't identify images

### ISSUE THREAD

**Issue by jameshilliard** [ReFirmLabs/binwalk#14]
This https://github.com/Lightsword1942/jungo-image/blob/master/MI424-WR-0018017A3ED9.bin is a dumped image that was created using this imaging script https://github.com/Lightsword1942/jungo-image/blob/master/jungo-image-2.py binwalk does not appear to identify anything.

**Comment by E3V3A** [comment]
[This](https://forum.openwrt.org/viewtopic.php?id=29344) thread should explain some of the *uncramfs-lzma* modified Jungo images. And the Gianpietro explanation [here](https://code.google.com/p/firmware-mod-kit/source/browse/src/uncramfs-lzma/README?r=866aa9d4f3768b3eb4464a100bfa5f19ddca0d3e):

> lzma-uncramfs is a modification of the uncramfs program to be able to
unpack cramfs images included in some openrg based home routers.
It includes lzma decompression and a different PAGE_CACHE_SIZE.
> 
> To successfully compile lzma-uncramfs an old version of lzma modified
by Jungo/OpenRG team is included.

And lzma-uncramfs sources [here](http://va.ler.io/dl/lzma-uncramfs.tar.gz). But I don't know if this is the same as that provided by James above...

**Comment by jameshilliard** [comment]
Did you test it on my router image? This is the firmware update file that I couldn't extract https://github.com/Lightsword1942/jungo-image/blob/master/4.0.16.1.56.0.10.11.6-MI424WR.rmt .

**Comment by E3V3A** [comment]
No I didn't. I just randomly came across this page and recalled that I had encountered something very similar in the past while dealing with and looking at various Jungo based crap FW on Pirelli routers. (Those guys should have a huge lawsuit up theirs, since their insecure FW is jam packed with security holes, not conforming to GPL and endangering entire nations.) You'll have to compile those sources to do the extraction, then mount it, AFAICR.

**Comment by jameshilliard** [comment]
Yeah, I think these Verizon routers are similar(they also don't conform to the GPL by releasing only the source for certain parts of the router rather than the compile environment that actually matches their firmware binaries). I compared the config file that is on the router with the one that is in their GPL package and the GPL one is missing lots of features/drivers.
