### ISSUE TITLE
It supports 8051 disassembly ??

### ISSUE THREAD

**Issue by abdelhak-mes** [ReFirmLabs/binwalk#228]
Please, does the binwalk support the 8051 disassembly ??

**Comment by devttys0** [comment]
No; binwalk uses Capstone for disassembly and I don't believe 8051 is supported by Capstone at the moment. But if there are some common bytes that frequently occur in 8051 assembly (e.g., function prologue/epilogue instructions), those can easily be added to binwalk's code signature detection.

**Comment by sundhaug92** [comment]
Capstone supports a lot of 1[6, 32 and 64-bit architectures](http://www.capstone-engine.org/arch.html) but does not have any support for 8051 nor other 8-bit architectures.
