### ISSUE TITLE
Best improvements for binwalk

### ISSUE THREAD

**Issue by numind06** [ReFirmLabs/binwalk#244]
Hi, I'd just want to recognize the big effort of this project but we still have some unsupported headers and compressed systems that I think we could fix with the help of all people interested.

In my particular case I hav some troubles with UBI headers, seems like a custom build, too much headers, the data has been extracted from NAND flash, after remove dummy blocks we get a clean 256MB bin dump, binwalk returns this data 

"UBI erase count header, version: 1, EC: 0x2, VID header offset: 0x800, data offset: 0x1000" 

but binwalk is only able to extract two empty folders, "0" and "webapp"
![captura](https://cloud.githubusercontent.com/assets/19439311/21296736/acda862c-c572-11e6-9e03-bee4f674fd6c.PNG)
Entropy shows many headers and splitted chunks of compressed data
![captura1](https://cloud.githubusercontent.com/assets/19439311/21296735/a5a8b9d2-c572-11e6-8da1-6d52ea9ff0c7.PNG)

So maybe if some more advanced user is willing to help with this, we could show all info needed and implement solution for each particular case and save all in a kind of library or database.

Many thanks in advance.

**Comment by devttys0** [comment]
Can you provide a copy of the firmware image?

**Comment by numind06** [comment]
Sure, If you tell me other way to upload file here (about 70MB), maximum size is 10 MB, I could paste a link from wetransfer for example...but need to be downloaded before 10 days or link will die.

**Comment by devttys0** [comment]
That would be fine!

**Comment by numind06** [comment]
Hi, sorry for delay, here is the link, only available for 7 days :(
https://we.tl/A0d78PSp9d
