### ISSUE TITLE
have some difficulties in binwalk

### ISSUE THREAD

**Issue by Poppylife** [ReFirmLabs/binwalk#245]
I used the latest binwalk to extract files form the firmware DIR-645 and DIR 815, there is a warning ：
WARNING: Extractor.execute failed to run external extractor 'sasquatch -p 1 -le -d '%%squashfs-root%%' '%e'': [Errno 2] No such file or directory.
There is also nothing in directory squashfs-root. Is there anything wrong ?

**Comment by devttys0** [comment]
The `sasquatch` extraction utility is not installed on your system.

https://github.com/devttys0/binwalk/blob/master/INSTALL.md#dependencies
