### ISSUE TITLE
Can binwalk  do static analysis of extracted firmwares?

### ISSUE THREAD

**Issue by bennyjiang** [ReFirmLabs/binwalk#246]
Can binwalk  do static analysis of extracted firmwares?need plug-ins?

**Comment by devttys0** [comment]
Do you mean can it perform a disassembly? Technically, yes (see the [--disasm option)](https://github.com/devttys0/binwalk/wiki/Usage#disasm)). It is not terribly useful for actual analysis though. Use an existing disassembler, like IDA or radare2.
