### ISSUE TITLE
Strengthen MySql Signatures

### ISSUE THREAD

**Issue by jogarock** [ReFirmLabs/binwalk#250]
The MySql signatures in the sql magic file can be updated to better describe the particular file formats and avoid false positives. There is some documentation for the table definition file format as well as for the ISAM compressed data file. This storage format has been replaced by InnoDB as of MySql 5.5 in 2010.

I can look into this as time permits.

**Comment by sundhaug92** [comment]
Could you provide some links with more information?

**Comment by sundhaug92** [comment]
@CoffeeExpress Reason for closing?
