### ISSUE TITLE
Python3 not extracting 

### ISSUE THREAD

**Issue by SElyPer** [ReFirmLabs/binwalk#313]
Using the latest master from git, when I try to extract a binary using python3, it only performs signature checks (does not seem to process any options).  Python2 using the same binwalk works just fine.
The command line I used for these captures are:
python3 /usr/local/bin/binwalk -e -M firmware.zip > python3.txt
python2.7 /usr/local/bin/binwalk -e -M firmware.zip > python27.txt

[python3.txt](https://github.com/ReFirmLabs/binwalk/files/1670268/python3.txt)
[python27.txt](https://github.com/ReFirmLabs/binwalk/files/1670269/python27.txt)

**Comment by JessicaFavin** [comment]
Hello @SElyPer 
I'm trying to work on this issue, could you provide me the zip file for further testing please ?
Thanks

**Comment by E3V3A** [comment]
@SElyPer ?

**Comment by SElyPer** [comment]
Good morning,
Unfortunately I no longer have that project so I'm not able to recreate the
issue.
Thanks

**Comment by E3V3A** [comment]
This may be related to #336. 
Otherwise close.

**Comment by 0xd3xt3r** [comment]
I have provided one such fix for on this pull request #426 see if this works for you
