### ISSUE TITLE
Binwalk stuck in infinite extraction loop

### ISSUE THREAD

**Issue by nhubbard** [ReFirmLabs/binwalk#317]
Hello binwalk developers!
I'm stuck trying to extract [this file](https://drive.google.com/file/d/16tMdYcWv0QfTcJoNMwU7K_bZzVKPbg0j/view?usp=sharing) using Binwalk. I have all optional expanders installed.
My log is [attached here](https://gist.github.com/nhubbard/d7cdde5eaecd1dc231de30d0745bf74f).
After extracting the file, and the `linux_safemode.itb` file within it (all the other files are Silverlight DLLs for the web interface), the `ramdisk` file contained within it is a EXT2 filesystem, but it just recursively extracts until it fails at some sort of corrupted CPIO archive.
Can anyone help fix this/extract this?

**Comment by decidedlygray** [comment]
Using that file to recreate and the latest binwalk there was no infinite loop extracting that firmware.

Binwalk version info:
```
$ git log
commit b28ee174a565339354148dcd266f289874073d7d
Author: devttys0 <cheffner@refirmlabs.com>
Date:   Tue May 22 10:40:00 2018 -0400
```

This bug may have been squashed
