### ISSUE TITLE
IDA 7.0 plugin incompatable

### ISSUE THREAD

**Issue by bmourit** [ReFirmLabs/binwalk#319]
The Binwalk IDA plugin is incompatible with versions 7.0+ of IDA. This is due to the requirement of using the new Actions API.

I have updated the plugin, which works fine for me on 7.0+, but it hasn't been tested on older version. If someone using an older version could verify this works (it should) then this could be pulled.

Here is the updated plugin: https://github.com/bmourit/binwalk/blob/patch-1/src/scripts/binida.py

I'll create a pull request as well.

**Comment by CoffeeExpress** [comment]
@bmourit Thanks for the patch. I'll see if we can find some time to take a look at it.

**Comment by bmourit** [comment]
No prob. Did it for my own use, but figured I'd share.
