### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by sfdye** [ReFirmLabs/binwalk#340]
Last Pypi release was on 2015.
https://pypi.org/project/binwalk/#history

**Comment by sfdye** [comment]
@devttys0

**Comment by anthraxx** [comment]
@devttys0 I would also appreciate a new git tag soon! thanks for all your work

**Comment by anthraxx** [comment]
@devttys0 ping

**Comment by sfdye** [comment]
Can we have an update please?

**Comment by E3V3A** [comment]
:tumbleweed:

**Comment by TobleMiner** [comment]
I second that. Most linux distributions will only distribute releases and there have been a lot of additions and fixes regarding file and data signatures. This tool does absolutely need another release.

Or is there any particular reason why there should not be a new release?
