### ISSUE TITLE
Problem with Ubuntu 18.04 and cramfsprogs

### ISSUE THREAD

**Issue by gerstrong** [ReFirmLabs/binwalk#343]
Unfortunately cramfsprogs does not exist in the Ubuntu repos anymore. Not sure how to install it or if it is really required...

**Comment by devttys0** [comment]
Only if you need to be able to extract CramFS file systems. Binwalk uses the `cramfsck` and `cramfsswap` utilities from this package, I'll have to see where to download them manually and update the `deps.sh` script.

**Comment by icommitfelonies** [comment]
This appears to still be an issue on Debian 9

**Comment by BeetleChunks** [comment]
On lubuntu I downloaded the deb package from https://packages.ubuntu.com/xenial/amd64/cramfsprogs/download and installed it manually (sudo dpkg -i ./cramfsprogs_1.1-6ubuntu1_amd64.deb).
