### ISSUE TITLE
Please correct typo "endianess" -> "endianness"

### ISSUE THREAD

**Issue by rhertzog** [ReFirmLabs/binwalk#351]
How to fix it quickly:
```
$ grep -r endianess -l | xargs sed -i -e 's/endianess/endianness/g'
$ git commit -a -m "Fix typo endianess -> endianness"
```

Thank you!

**Comment by E3V3A** [comment]
@devttys0 @CoffeeExpress 
Can you guys do this? 
It's a trivial fix and after years of looking at the same typos, one eventually get annoyed.
