### ISSUE TITLE
binwalk list compressed type without extracting

### ISSUE THREAD

**Issue by jayenashar** [ReFirmLabs/binwalk#358]
Hi there,

I want to extract a gzip-compressed cpio archive from a binary file.  However, there are many false gzip magic in the binary file, so `binwalk --include gz --extract file` results in using too much disk space as some of the false gzips are never-ending.

I tried `binwalk --extract --include 'last modified' file` but that didn't find anything, despite `--include gz` listing things like "gzip compressed data, from Unix, last modified: 2018-09-25 08:39:07".

What can I do?

Thanks,
Jayen

**Comment by E3V3A** [comment]
Please read the extended answer by `devttys0` in #367.  
Perhaps you will find some helpful hints there.

**Comment by jayenashar** [comment]
thanks for the pointer.  it seems like `devttyS0`'s answer in #367 is more about changing the magic that is happening and why it is difficult.  what i'm asking is how to use the already-existing magic to more selectively choose what to extract.

i ended up solving this by writing a wrapper script to `grep 'last modified'` and then individually extracting each matching gz by offset.
