### ISSUE TITLE
A way to tell binwalk to skip extraction of an specific file type

### ISSUE THREAD

**Issue by 0xfede7c8** [ReFirmLabs/binwalk#369]
An example use case is issue #368.

There is a bug on extraction of those ISO files, but I want to keep using binwalk for the rest of the files.
It would be great to tell extractor to skip ISO files.

**Comment by 0xfede7c8** [comment]
This is not a bug. It's a feature that comes to prevent some bug cases. Also useful for other cases also. #368 is a bug definitely.

**Comment by devttys0** [comment]
The [--exclude](https://github.com/ReFirmLabs/binwalk/wiki/Usage#-x---excludefilter) option allows you to specify signatures to ignore.

**Comment by 0xfede7c8** [comment]
Oh, typical case of not RTFM :)
I didn't know the existance of --exclude or --fexclude.
Sorry. Closing.
