### ISSUE TITLE
Please merge all PRs!

### ISSUE THREAD

**Issue by E3V3A** [ReFirmLabs/binwalk#372]
I've gone through all the currently available PRs and they can all be merged with little effect and a lot of improved detection features. 

Any good reason why these have not already been merged? (One is already 10 month old!)

**Comment by CoffeeExpress** [comment]
@E3V3A You're right, we need to make some progress on that. The previous year has been hectic at ReFirm Labs, and we need to take some time to give some more attention to Binwalk. I'll chat with @devttys0 and see what we can do.

**Comment by E3V3A** [comment]
Great to hear! Thank you guys for paying attention.
