### ISSUE TITLE
Is CoffeExpress a broken bot?

### ISSUE THREAD

**Issue by E3V3A** [ReFirmLabs/binwalk#373]
It seem that the user: https://github.com/CoffeeExpress is mislabeling just about every issue here.
Is this a broken bot or someone who just doesn't have a clue what he/she's doing?

**Comment by CoffeeExpress** [comment]
![image](https://user-images.githubusercontent.com/34044521/49081821-feed4e00-f215-11e8-944c-0b19c63d73d6.png)

**Comment by E3V3A** [comment]
BTW. Some of the emojis in the issue labels are not displaying correctly!

**Comment by CoffeeExpress** [comment]
Which ones?

**Comment by E3V3A** [comment]
The one in support
