### ISSUE TITLE
Extraction issue on PEM certificates (Ubuntu 18.04)

### ISSUE THREAD

**Issue by zMathieu** [ReFirmLabs/binwalk#379]
Hello,

When I try to extract certificates from files, binwalk doesn't extract them.

I tried using binwalk with the python API (python2 and python3).

On my own computer, the extraction works with the python3 API and CLI command (installed via `apt install -y binwalk`) but not with the python2 API.

On a Ubuntu 18.04 docker, it does not work with python2, nor with python3.

I think this issue could be related to the issue [#313](https://github.com/ReFirmLabs/binwalk/issues/313).

## Steps to reproduce

Go into an Ubuntu 18.04 docker :

```shell
sudo docker run -ti ubuntu:18.04 /bin/bash
```

Install binwalk :

```shell
apt update
apt install -y python wget unzip
wget https://github.com/ReFirmLabs/binwalk/archive/master.zip
unzip master.zip
cd binwalk-master && python setup.py install
```

Try to extract PEM certificate from a file containing certificates, for example `/etc/ssl/cert/ca-certificates.crt` :

```shell
binwalk -e /etc/ssl/cert/ca-certificates.crt
```

---

Thanks for your help.

**Comment by 0xXA** [comment]
> Hello,
> 
> When I try to extract certificates from files, binwalk doesn't extract them.
> 
> I tried using binwalk with the python API (python2 and python3).
> 
> On my own computer, the extraction works with the python3 API and CLI command (installed via `apt install -y binwalk`) but not with the python2 API.
> 
> On a Ubuntu 18.04 docker, it does not work with python2, nor with python3.
> 
> I think this issue could be related to the issue [#313](https://github.com/ReFirmLabs/binwalk/issues/313).
> 
> ## Steps to reproduce
> Go into an Ubuntu 18.04 docker :
> 
> ```shell
> sudo docker run -ti ubuntu:18.04 /bin/bash
> ```
> 
> Install binwalk :
> 
> ```shell
> apt update
> apt install -y python wget unzip
> wget https://github.com/ReFirmLabs/binwalk/archive/master.zip
> unzip master.zip
> cd binwalk-master && python setup.py install
> ```
> 
> Try to extract PEM certificate from a file containing certificates, for example `/etc/ssl/cert/ca-certificates.crt` :
> 
> ```shell
> binwalk -e /etc/ssl/cert/ca-certificates.crt
> ```
> 
> Thanks for your help.

Package manager provides old version of binwalk it's better to install it from sources
You should build it from sources with below commands.

```
# git clone https://github.com/ReFirmLabs/binwalk
# cd binwalk
# ./deps.sh
# if [ -e `which python` ]; then \
sudo python setup.py install; \
elif [ -e `which python3` ]; then \
sudo python3 setup.py install; \
fi
```

**Comment by devttys0** [comment]
Binwalk supports identification of certificates and PEM files, but does not support extraction of those files. Generally speaking, binwalk doesn't support extraction of any files or data that are already reduced to their standard format (e.g., PEM files, ELF files, raw code, etc).

What you want to do is data carving, which binwalk *can* do, but that is not its primary purpose and there are better tools available for data carving. There was a fairly lengthy discussion on the subject of data carving vs extraction in issue #376.

**Comment by RoganDawes** [comment]
Just updating this to point to the correct issue where carving was discussed: [#367](https://github.com/ReFirmLabs/binwalk/issues/367)
