### ISSUE TITLE
Better way to extract files that doesn't need processing

### ISSUE THREAD

**Issue by tyilo** [ReFirmLabs/binwalk#38]
Currently if you run `binwalk -e` on a file containing jpeg files, `binwalk` will create an empty folder.

To actually extract the files you have to make a dummy entry in `~/.binwalk/config/extract.conf`, like:

```
jpeg:jpg:echo
```

Would it be possible to either make `-e` extract all recognizable file types or provide a new option which does this?

**Comment by kamil-HFC** [comment]
Hi. What about file sizing? For example, some piece of results: 
7418159       0x71312F        HTML document header
7428508       0x71599C        HTML document footer
7428597       0x7159F5        HTML document header
7433720       0x716DF8        HTML document footer
7433802       0x716E4A        HTML document header
7436683       0x71798B        HTML document footer
7436770       0x7179E2        HTML document header
Scannig says, that 71599C file have to take 89bytes, but extracted with dd option takes 646328. Thiese are concatenated files. Is there any way to determinate, where is beginning/end of each file? This suggest me a second question. This result is from firmware, for cable modem. I have here a one big file extracted froma lzma block of data. As far as i know, lzma is not supporting to compress multiply files into a one file. How can i extract it properly? I mean to split each file in exact point?

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
496           0x1F0           eCos kernel exception handler, architecture: MIPS, exception vector table base address: 0x80000300
24752         0x60B0          Certificate in DER format (x509 v3), header length: 4, sequence length: 32
103480        0x19438         Certificate in DER format (x509 v3), header length: 4, sequence length: 128
5625066       0x55D4EA        Copyright string: "Copyright (c) 2003-2009 Broadcom Corporation"
5626751       0x55DB7F        Copyright string: "Copyright (c) 1999 - 2009 Broadcom Corporation"
5658120       0x565608        Neighborly text, "Neighbor Discovery Thread for _/   _/"
5658351       0x5656EF        Copyright string: "Copyright (c) 1999 - 2009 Broadcom Corporation"
5721954       0x574F62        Unix path: /t/T/y/Y as 'true'; 0/f/F/n/N as 'false'.
5787340       0x584ECC        Neighborly text, "NeighborSolicitationterRenumbering"
5787364       0x584EE4        Neighborly text, "NeighborAdvertisementtionQuery"
5787467       0x584F4B        Neighborly text, "NeighborDiscoverySolicitationisement"
5787507       0x584F73        Neighborly text, "NeighborDiscoveryAdvertisementt"
5806424       0x589958        HTML document header
5806645       0x589A35        HTML document footer
5825124       0x58E264        HTML document header
5825873       0x58E551        HTML document footer
5825884       0x58E55C        HTML document header
5826135       0x58E657        HTML document footer
5826284       0x58E6EC        HTML document header
...
