### ISSUE TITLE
El capitan error

### ISSUE THREAD

**Issue by infoiOSX** [ReFirmLabs/binwalk#384]
Last login: Tue Feb  5 00:37:17 on ttys000
MacBookigdadmin:~ gdadmin$ ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
==> You are using macOS 10.11.
==> We (and Apple) do not provide support for this old version.
This installation may not succeed.
After installation, you will encounter build failures and other breakages.
Please create pull requests instead of asking for help on Homebrew's
GitHub, Discourse, Twitter or IRC. As you are running this old version,
you are responsible for resolving any issues you experience.

==> This script will install:
/usr/local/bin/brew
/usr/local/share/doc/homebrew
/usr/local/share/man/man1/brew.1
/usr/local/share/zsh/site-functions/_brew
/usr/local/etc/bash_completion.d/brew
/usr/local/Homebrew
==> The following new directories will be created:
/usr/local/var
/usr/local/opt
/usr/local/share/zsh
/usr/local/share/zsh/site-functions
/usr/local/var/homebrew
/usr/local/var/homebrew/linked
/usr/local/Cellar
/usr/local/Caskroom
/usr/local/Homebrew
/usr/local/Frameworks

Press RETURN to continue or any other key to abort
==> /usr/bin/sudo /bin/mkdir -p /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/chmod g+rwx /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/chmod 755 /usr/local/share/zsh /usr/local/share/zsh/site-functions
==> /usr/bin/sudo /usr/sbin/chown gdadmin /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /usr/bin/chgrp admin /usr/local/var /usr/local/opt /usr/local/share/zsh /usr/local/share/zsh/site-functions /usr/local/var/homebrew /usr/local/var/homebrew/linked /usr/local/Cellar /usr/local/Caskroom /usr/local/Homebrew /usr/local/Frameworks
==> /usr/bin/sudo /bin/mkdir -p /Users/gdadmin/Library/Caches/Homebrew
==> /usr/bin/sudo /bin/chmod g+rwx /Users/gdadmin/Library/Caches/Homebrew
==> /usr/bin/sudo /usr/sbin/chown gdadmin /Users/gdadmin/Library/Caches/Homebrew
==> Downloading and installing Homebrew...
remote: Enumerating objects: 62, done.
remote: Counting objects: 100% (62/62), done.
remote: Compressing objects: 100% (35/35), done.
remote: Total 118340 (delta 30), reused 42 (delta 27), pack-reused 118278
Receiving objects: 100% (118340/118340), 27.98 MiB | 5.67 MiB/s, done.
Resolving deltas: 100% (86424/86424), done.
From https://github.com/Homebrew/brew
 * [new branch]      master     -> origin/master
 * [new tag]         0.1        -> 0.1
 * [new tag]         0.2        -> 0.2
 * [new tag]         0.3        -> 0.3
 * [new tag]         0.4        -> 0.4
 * [new tag]         0.5        -> 0.5
 * [new tag]         0.6        -> 0.6
 * [new tag]         0.7        -> 0.7
 * [new tag]         0.7.1      -> 0.7.1
 * [new tag]         0.8        -> 0.8
 * [new tag]         0.8.1      -> 0.8.1
 * [new tag]         0.9        -> 0.9
 * [new tag]         0.9.1      -> 0.9.1
 * [new tag]         0.9.2      -> 0.9.2
 * [new tag]         0.9.3      -> 0.9.3
 * [new tag]         0.9.4      -> 0.9.4
 * [new tag]         0.9.5      -> 0.9.5
 * [new tag]         0.9.8      -> 0.9.8
 * [new tag]         0.9.9      -> 0.9.9
 * [new tag]         1.0.0      -> 1.0.0
 * [new tag]         1.0.1      -> 1.0.1
 * [new tag]         1.0.2      -> 1.0.2
 * [new tag]         1.0.3      -> 1.0.3
 * [new tag]         1.0.4      -> 1.0.4
 * [new tag]         1.0.5      -> 1.0.5
 * [new tag]         1.0.6      -> 1.0.6
 * [new tag]         1.0.7      -> 1.0.7
 * [new tag]         1.0.8      -> 1.0.8
 * [new tag]         1.0.9      -> 1.0.9
 * [new tag]         1.1.0      -> 1.1.0
 * [new tag]         1.1.1      -> 1.1.1
 * [new tag]         1.1.10     -> 1.1.10
 * [new tag]         1.1.11     -> 1.1.11
 * [new tag]         1.1.12     -> 1.1.12
 * [new tag]         1.1.13     -> 1.1.13
 * [new tag]         1.1.2      -> 1.1.2
 * [new tag]         1.1.3      -> 1.1.3
 * [new tag]         1.1.4      -> 1.1.4
 * [new tag]         1.1.5      -> 1.1.5
 * [new tag]         1.1.6      -> 1.1.6
 * [new tag]         1.1.7      -> 1.1.7
 * [new tag]         1.1.8      -> 1.1.8
 * [new tag]         1.1.9      -> 1.1.9
 * [new tag]         1.2.0      -> 1.2.0
 * [new tag]         1.2.1      -> 1.2.1
 * [new tag]         1.2.2      -> 1.2.2
 * [new tag]         1.2.3      -> 1.2.3
 * [new tag]         1.2.4      -> 1.2.4
 * [new tag]         1.2.5      -> 1.2.5
 * [new tag]         1.2.6      -> 1.2.6
 * [new tag]         1.3.0      -> 1.3.0
 * [new tag]         1.3.1      -> 1.3.1
 * [new tag]         1.3.2      -> 1.3.2
 * [new tag]         1.3.3      -> 1.3.3
 * [new tag]         1.3.4      -> 1.3.4
 * [new tag]         1.3.5      -> 1.3.5
 * [new tag]         1.3.6      -> 1.3.6
 * [new tag]         1.3.7      -> 1.3.7
 * [new tag]         1.3.8      -> 1.3.8
 * [new tag]         1.3.9      -> 1.3.9
 * [new tag]         1.4.0      -> 1.4.0
 * [new tag]         1.4.1      -> 1.4.1
 * [new tag]         1.4.2      -> 1.4.2
 * [new tag]         1.4.3      -> 1.4.3
 * [new tag]         1.5.0      -> 1.5.0
 * [new tag]         1.5.1      -> 1.5.1
 * [new tag]         1.5.10     -> 1.5.10
 * [new tag]         1.5.11     -> 1.5.11
 * [new tag]         1.5.12     -> 1.5.12
 * [new tag]         1.5.13     -> 1.5.13
 * [new tag]         1.5.14     -> 1.5.14
 * [new tag]         1.5.2      -> 1.5.2
 * [new tag]         1.5.3      -> 1.5.3
 * [new tag]         1.5.4      -> 1.5.4
 * [new tag]         1.5.5      -> 1.5.5
 * [new tag]         1.5.6      -> 1.5.6
 * [new tag]         1.5.7      -> 1.5.7
 * [new tag]         1.5.8      -> 1.5.8
 * [new tag]         1.5.9      -> 1.5.9
 * [new tag]         1.6.0      -> 1.6.0
 * [new tag]         1.6.1      -> 1.6.1
 * [new tag]         1.6.10     -> 1.6.10
 * [new tag]         1.6.11     -> 1.6.11
 * [new tag]         1.6.12     -> 1.6.12
 * [new tag]         1.6.13     -> 1.6.13
 * [new tag]         1.6.14     -> 1.6.14
 * [new tag]         1.6.15     -> 1.6.15
 * [new tag]         1.6.16     -> 1.6.16
 * [new tag]         1.6.17     -> 1.6.17
 * [new tag]         1.6.2      -> 1.6.2
 * [new tag]         1.6.3      -> 1.6.3
 * [new tag]         1.6.4      -> 1.6.4
 * [new tag]         1.6.5      -> 1.6.5
 * [new tag]         1.6.6      -> 1.6.6
 * [new tag]         1.6.7      -> 1.6.7
 * [new tag]         1.6.8      -> 1.6.8
 * [new tag]         1.6.9      -> 1.6.9
 * [new tag]         1.7.0      -> 1.7.0
 * [new tag]         1.7.1      -> 1.7.1
 * [new tag]         1.7.2      -> 1.7.2
 * [new tag]         1.7.3      -> 1.7.3
 * [new tag]         1.7.4      -> 1.7.4
 * [new tag]         1.7.5      -> 1.7.5
 * [new tag]         1.7.6      -> 1.7.6
 * [new tag]         1.7.7      -> 1.7.7
 * [new tag]         1.8.0      -> 1.8.0
 * [new tag]         1.8.1      -> 1.8.1
 * [new tag]         1.8.2      -> 1.8.2
 * [new tag]         1.8.3      -> 1.8.3
 * [new tag]         1.8.4      -> 1.8.4
 * [new tag]         1.8.5      -> 1.8.5
 * [new tag]         1.8.6      -> 1.8.6
 * [new tag]         1.9.0      -> 1.9.0
 * [new tag]         1.9.1      -> 1.9.1
 * [new tag]         1.9.2      -> 1.9.2
 * [new tag]         1.9.3      -> 1.9.3
 * [new tag]         2.0.0      -> 2.0.0
HEAD is now at 81b6623 Merge pull request #5668 from GauthamGoli/update-report-quiet-arg
==> Downloading https://homebrew.bintray.com/bottles-portable-ruby/portable-ruby-2.3.7.mavericks.bottle.tar.gz
######################################################################## 100.0%
==> Pouring portable-ruby-2.3.7.mavericks.bottle.tar.gz
==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Tapping homebrew/core
Cloning into '/usr/local/Homebrew/Library/Taps/homebrew/homebrew-core'...
remote: Enumerating objects: 4912, done.
remote: Counting objects: 100% (4912/4912), done.
remote: Compressing objects: 100% (4711/4711), done.
remote: Total 4912 (delta 48), reused 331 (delta 9), pack-reused 0
Receiving objects: 100% (4912/4912), 3.96 MiB | 3.49 MiB/s, done.
Resolving deltas: 100% (48/48), done.
Tapped 2 commands and 4697 formulae (4,953 files, 12.3MB).
Already up-to-date.
==> Installation successful!

==> Homebrew has enabled anonymous aggregate formulae and cask analytics.
Read the analytics documentation (and how to opt-out) here:
  https://docs.brew.sh/Analytics

==> Homebrew is run entirely by unpaid volunteers. Please consider donating:
  https://github.com/Homebrew/brew#donations
==> Next steps:
- Run `brew help` to get started
- Further documentation: 
    https://docs.brew.sh
MacBookigdadmin:~ gdadmin$ brew install binwalk
Updating Homebrew...
Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.

==> Installing dependencies for git: gettext and pcre2
==> Installing git dependency: gettext
==> Downloading https://homebrew.bintray.com/bottles/gettext-0.19.8.1.el_capitan
######################################################################## 100.0%
==> Pouring gettext-0.19.8.1.el_capitan.bottle.tar.gz
==> Caveats
gettext is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD gettext library & some software gets confused if both are in the library path.

If you need to have gettext first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

For compilers to find gettext you may need to set:
  export LDFLAGS="-L/usr/local/opt/gettext/lib"
  export CPPFLAGS="-I/usr/local/opt/gettext/include"

==> Summary
🍺  /usr/local/Cellar/gettext/0.19.8.1: 1,934 files, 16.9MB
==> Installing git dependency: pcre2
==> Downloading https://homebrew.bintray.com/bottles/pcre2-10.32.el_capitan.bott
######################################################################## 100.0%
==> Pouring pcre2-10.32.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/pcre2/10.32: 224 files, 5.5MB
==> Installing git
==> Downloading https://www.kernel.org/pub/software/scm/git/git-2.20.1.tar.xz
==> Downloading from https://mirrors.edge.kernel.org/pub/software/scm/git/git-2.
######################################################################## 100.0%
==> make install prefix=/usr/local/Cellar/git/2.20.1 sysconfdir=/usr/local/etc C
==> make CC=clang CFLAGS= LDFLAGS=
==> make clean
==> make
==> make test
==> make CC=clang CFLAGS= LDFLAGS=
==> Downloading https://www.kernel.org/pub/software/scm/git/git-manpages-2.20.1.
==> Downloading from https://mirrors.edge.kernel.org/pub/software/scm/git/git-ma
######################################################################## 100.0%
==> Downloading https://www.kernel.org/pub/software/scm/git/git-htmldocs-2.20.1.
==> Downloading from https://mirrors.edge.kernel.org/pub/software/scm/git/git-ht
######################################################################## 100.0%
==> Downloading https://cpan.metacpan.org/authors/id/R/RJ/RJBS/Net-SMTP-SSL-1.04
######################################################################## 100.0%
==> Caveats
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
==> Summary
🍺  /usr/local/Cellar/git/2.20.1: 1,527 files, 41.6MB, built in 4 minutes 3 seconds
==> `brew cleanup` has not been run in 30 days, running now...
==> Caveats
==> gettext
gettext is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD gettext library & some software gets confused if both are in the library path.

If you need to have gettext first in your PATH run:
  echo 'export PATH="/usr/local/opt/gettext/bin:$PATH"' >> ~/.bash_profile

For compilers to find gettext you may need to set:
  export LDFLAGS="-L/usr/local/opt/gettext/lib"
  export CPPFLAGS="-I/usr/local/opt/gettext/include"

==> git
Bash completion has been installed to:
  /usr/local/etc/bash_completion.d

zsh completions and functions have been installed to:
  /usr/local/share/zsh/site-functions

Emacs Lisp files have been installed to:
  /usr/local/share/emacs/site-lisp/git
Warning: You are using macOS 10.11.
We (and Apple) do not provide support for this old version.
You will encounter build failures with some formulae.
Please create pull requests instead of asking for help on Homebrew's GitHub,
Discourse, Twitter or IRC. You are responsible for resolving any issues you
experience, as you are running this old version.

==> Installing dependencies for binwalk: pcre, swig, gmp, isl, mpfr, libmpc, gcc, p7zip, pkg-config, gdbm, openssl, readline, sqlite, xz, python and ssdeep
==> Installing binwalk dependency: pcre
==> Downloading https://homebrew.bintray.com/bottles/pcre-8.42.el_capitan.bottle
######################################################################## 100.0%
==> Pouring pcre-8.42.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/pcre/8.42: 204 files, 5.4MB
==> Installing binwalk dependency: swig
==> Downloading https://homebrew.bintray.com/bottles/swig-3.0.12.el_capitan.bott
######################################################################## 100.0%
==> Pouring swig-3.0.12.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/swig/3.0.12: 755 files, 5.5MB
==> Installing binwalk dependency: gmp
==> Downloading https://homebrew.bintray.com/bottles/gmp-6.1.2_2.el_capitan.bott
######################################################################## 100.0%
==> Pouring gmp-6.1.2_2.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/gmp/6.1.2_2: 18 files, 3.1MB
==> Installing binwalk dependency: isl
==> Downloading https://homebrew.bintray.com/bottles/isl-0.20.el_capitan.bottle.
######################################################################## 100.0%
==> Pouring isl-0.20.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/isl/0.20: 71 files, 4.0MB
==> Installing binwalk dependency: mpfr
==> Downloading https://homebrew.bintray.com/bottles/mpfr-4.0.1.el_capitan.bottl
######################################################################## 100.0%
==> Pouring mpfr-4.0.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/mpfr/4.0.1: 28 files, 4.6MB
==> Installing binwalk dependency: libmpc
==> Downloading https://homebrew.bintray.com/bottles/libmpc-1.1.0.el_capitan.bot
######################################################################## 100.0%
==> Pouring libmpc-1.1.0.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/libmpc/1.1.0: 12 files, 359.6KB
==> Installing binwalk dependency: gcc
==> Downloading https://ftp.gnu.org/gnu/gcc/gcc-8.2.0/gcc-8.2.0.tar.xz
######################################################################## 100.0%
==> Patching
patching file gcc/graphite.h
==> ../configure --build=x86_64-apple-darwin15.6.0 --prefix=/usr/local/Cellar/gc
==> make BOOT_LDFLAGS=-Wl,-headerpad_max_install_names
==> make install
🍺  /usr/local/Cellar/gcc/8.2.0: 1,493 files, 349.6MB, built in 205 minutes 48 seconds
==> Installing binwalk dependency: p7zip
==> Downloading https://homebrew.bintray.com/bottles/p7zip-16.02_1.el_capitan.bo
######################################################################## 100.0%
==> Pouring p7zip-16.02_1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/p7zip/16.02_1: 103 files, 4.8MB
==> Installing binwalk dependency: pkg-config
==> Downloading https://homebrew.bintray.com/bottles/pkg-config-0.29.2.el_capita
######################################################################## 100.0%
==> Pouring pkg-config-0.29.2.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/pkg-config/0.29.2: 11 files, 627KB
==> Installing binwalk dependency: gdbm
==> Downloading https://ftp.gnu.org/gnu/gdbm/gdbm-1.18.1.tar.gz
######################################################################## 100.0%
==> ./configure --disable-silent-rules --without-readline --prefix=/usr/local/Ce
==> make install
🍺  /usr/local/Cellar/gdbm/1.18.1: 20 files, 591.5KB, built in 1 minute 14 seconds
==> Installing binwalk dependency: openssl
==> Downloading https://www.openssl.org/source/openssl-1.0.2q.tar.gz
######################################################################## 100.0%
==> perl ./Configure --prefix=/usr/local/Cellar/openssl/1.0.2q --openssldir=/usr
==> make depend
==> make
==> make test
==> make install MANDIR=/usr/local/Cellar/openssl/1.0.2q/share/man MANSUFFIX=ssl
==> Caveats
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

openssl is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have openssl first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl/include"

For pkg-config to find openssl you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/openssl/1.0.2q: 1,786 files, 12.2MB, built in 17 minutes 16 seconds
==> Installing binwalk dependency: readline
==> Downloading https://ftp.gnu.org/gnu/readline/readline-8.0.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/readline/8.0.0
==> make install
==> Caveats
readline is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

For compilers to find readline you may need to set:
  export LDFLAGS="-L/usr/local/opt/readline/lib"
  export CPPFLAGS="-I/usr/local/opt/readline/include"

For pkg-config to find readline you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/readline/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/readline/8.0.0: 48 files, 1.5MB, built in 1 minute 28 seconds
==> Installing binwalk dependency: sqlite
==> Downloading https://sqlite.org/2018/sqlite-autoconf-3260000.tar.gz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/sqlite/3.26.0_1 --enable-dynamic-exte
==> make install
==> Caveats
sqlite is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have sqlite first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.bash_profile

For compilers to find sqlite you may need to set:
  export LDFLAGS="-L/usr/local/opt/sqlite/lib"
  export CPPFLAGS="-I/usr/local/opt/sqlite/include"

For pkg-config to find sqlite you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/sqlite/lib/pkgconfig"

==> Summary
🍺  /usr/local/Cellar/sqlite/3.26.0_1: 11 files, 3.8MB, built in 2 minutes 26 seconds
==> Installing binwalk dependency: xz
==> Downloading https://homebrew.bintray.com/bottles/xz-5.2.4.el_capitan.bottle.
######################################################################## 100.0%
==> Pouring xz-5.2.4.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/xz/5.2.4: 92 files, 1MB
==> Installing binwalk dependency: python
==> Downloading https://www.python.org/ftp/python/3.7.2/Python-3.7.2.tgz
######################################################################## 100.0%
==> ./configure --prefix=/usr/local/Cellar/python/3.7.2_1 --enable-ipv6 --dataro
==> make
==> make install PYTHONAPPSDIR=/usr/local/Cellar/python/3.7.2_1
==> make frameworkinstallextras PYTHONAPPSDIR=/usr/local/Cellar/python/3.7.2_1/s
==> Downloading https://files.pythonhosted.org/packages/37/1b/b25507861991beeade
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/45/ae/8a0ad77defb7cc903f
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/d8/55/221a530d66bf78e729
######################################################################## 100.0%
==> /usr/local/Cellar/python/3.7.2_1/bin/python3 -s setup.py --no-user-cfg insta
==> /usr/local/Cellar/python/3.7.2_1/bin/python3 -s setup.py --no-user-cfg insta
==> /usr/local/Cellar/python/3.7.2_1/bin/python3 -s setup.py --no-user-cfg insta
==> Caveats
Python has been installed as
  /usr/local/bin/python3

Unversioned symlinks `python`, `python-config`, `pip` etc. pointing to
`python3`, `python3-config`, `pip3` etc., respectively, have been installed into
  /usr/local/opt/python/libexec/bin

If you need Homebrew's Python 2.7 run
  brew install python@2

You can install Python packages with
  pip3 install <package>
They will install into the site-package directory
  /usr/local/lib/python3.7/site-packages

See: https://docs.brew.sh/Homebrew-and-Python
==> Summary
🍺  /usr/local/Cellar/python/3.7.2_1: 8,437 files, 118MB, built in 8 minutes 46 seconds
==> Installing binwalk dependency: ssdeep
==> Downloading https://homebrew.bintray.com/bottles/ssdeep-2.14.1.el_capitan.bo
######################################################################## 100.0%
==> Pouring ssdeep-2.14.1.el_capitan.bottle.tar.gz
🍺  /usr/local/Cellar/ssdeep/2.14.1: 15 files, 144.8KB
==> Installing binwalk
==> Downloading https://github.com/ReFirmLabs/binwalk/archive/v2.1.1.tar.gz
==> Downloading from https://codeload.github.com/ReFirmLabs/binwalk/tar.gz/v2.1.
######################################################################## 100.0%
==> Downloading https://files.pythonhosted.org/packages/45/ba/2a781ebbb0cd7962cc
######################################################################## 100.0%
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Ce
==> Downloading https://files.pythonhosted.org/packages/07/76/7e844757b9f3bf5ab9
######################################################################## 100.0%
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Ce
==> python3 -c import setuptools... --no-user-cfg install --prefix=/usr/local/Ce
Warning: binwalk dependency gcc was built with a different C++ standard
library (libstdc++ from clang). This may cause problems at runtime.
🍺  /usr/local/Cellar/binwalk/2.1.1_6: 2,060 files, 81.3MB, built in 31 minutes 2 seconds
==> Caveats
==> openssl
A CA file has been bootstrapped using certificates from the SystemRoots
keychain. To add additional certificates (e.g. the certificates added in
the System keychain), place .pem files in
  /usr/local/etc/openssl/certs

and run
  /usr/local/opt/openssl/bin/c_rehash

openssl is keg-only, which means it was not symlinked into /usr/local,
because Apple has deprecated use of OpenSSL in favor of its own TLS and crypto libraries.

If you need to have openssl first in your PATH run:
  echo 'export PATH="/usr/local/opt/openssl/bin:$PATH"' >> ~/.bash_profile

For compilers to find openssl you may need to set:
  export LDFLAGS="-L/usr/local/opt/openssl/lib"
  export CPPFLAGS="-I/usr/local/opt/openssl/include"

For pkg-config to find openssl you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/openssl/lib/pkgconfig"

==> readline
readline is keg-only, which means it was not symlinked into /usr/local,
because macOS provides the BSD libedit library, which shadows libreadline.
In order to prevent conflicts when programs look for libreadline we are
defaulting this GNU Readline installation to keg-only.

For compilers to find readline you may need to set:
  export LDFLAGS="-L/usr/local/opt/readline/lib"
  export CPPFLAGS="-I/usr/local/opt/readline/include"

For pkg-config to find readline you may need to set:
  export PKG_CONFIG_PATH="/usr/local/opt/readline/lib/pkgconfig"

==> sqlite
sqlite is keg-only, which means it was not symlinked into /usr/local,
because macOS provides an older sqlite3.

If you need to have sqlite first in your PATH run:
  echo 'export PATH="/usr/local/opt/sqlite/bin:$PATH"' >> ~/.bash_profile

For compilers to find sqlite you may need to set:
  export LDFLAGS="-L/usr/local/opt/sqlite/lib"

ERROR OPEN ANT FIRMWARE......MacBookigdadmin:~ gdadmin$ binwalk /Users/gdadmin/Desktop/firmware.bin 

Signature Exception: 'utf-8' codec can't decode byte 0x86 in position 23: invalid start byte
----------------------------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/local/Cellar/binwalk/2.1.1_6/libexec/lib/python3.7/site-packages/binwalk/core/module.py", line 548, in main
    self.init()
  File "/usr/local/Cellar/binwalk/2.1.1_6/libexec/lib/python3.7/site-packages/binwalk/modules/signature.py", line 98, in init
    self.magic.load(f)
  File "/usr/local/Cellar/binwalk/2.1.1_6/libexec/lib/python3.7/site-packages/binwalk/core/magic.py", line 794, in load
    lines = fp.readlines()
  File "/usr/local/Cellar/python/3.7.2_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/codecs.py", line 322, in decode
    (result, consumed) = self._buffer_decode(data, self.errors, final)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0x86 in position 23: invalid start byte
----------------------------------------------------------------------------------------------------

MacBookigdadmin:~ gdadmin$

**Comment by CoffeeExpress** [comment]
The homebrew package isn't maintained by ReFirm. OS X isn't really supported either.
