### ISSUE TITLE
.binwalk directory being created in home.

### ISSUE THREAD

**Issue by cedws** [ReFirmLabs/binwalk#390]
It appears the XDG Base Directory Specification was addressed in #216 but a `.binwalk` directory is still being created in my home directory each time I run binwalk.

Version: `v2.1.1`

**Comment by barskern** [comment]
Same here (`v2.1.1`).

**Comment by c-edw** [comment]
Eh? There hasn't been a release in *4 years*?

**Comment by barskern** [comment]
No, [the last release `v2.1.1` was December 2015](https://github.com/ReFirmLabs/binwalk/releases/tag/v2.1.1).

**Comment by CoffeeExpress** [comment]
It's best to work off the latest revision of the github repo instead of trying to install a package release.
