### ISSUE TITLE
How to run  binwalk in multithreading

### ISSUE THREAD

**Issue by ykla** [ReFirmLabs/binwalk#401]
How to run binwalk in multithreading? Likes I compiling kernel add "-j4" if you has 4 core CPUs. If can't, please support it. Thinks a lot.

**Comment by devttys0** [comment]
Binwalk does not support multithreading, and it would be difficult to add to binwalk safely. The best option would be to create a thread or process for each file that binwalk analyzes, but this would only help when analyzing multiple files. This could be done with a separate script using the binwalk API, but we have no intention of adding multithreading support at this time.
