### ISSUE TITLE
API Issue: Recursive extraction using Binwalk API possible?

### ISSUE THREAD

**Issue by HassamK97** [ReFirmLabs/binwalk#405]
Hi, I am using binwalk API to perform firmware extraction. When extraction is performed it only returns some extracted files and not the complete file system. Not like the tool which returns complete file system after recursive extraction. 

`binwalk -M -e dlink_DCS_930L.bin`

This command recursively extracts binary file and displays following information in extracted folder:
![Screenshot from 2019-05-09 14-05-31](https://user-images.githubusercontent.com/50437723/57444673-1a9b5c80-726a-11e9-8535-d883febbf1ad.png)

But if I perform extraction from binwalk API, it doesn't extract recursively. The following code is used for performing firmware extraction using API:

`for module in binwalk.scan('dlink_DCS_930L.bin',  signature=True, quiet=True, extract=True):`

It does not display the complete file system of the firmware like above. The result is as follows:
![Screenshot from 2019-05-09 14-06-27](https://user-images.githubusercontent.com/50437723/57444906-a4e3c080-726a-11e9-8970-8f644d0aa154.png)

Is there any rule or any specific method that performs recursive extraction using binwalk Python API? Kindly acknowledge.

**Comment by Kruxinator** [comment]
Use
`for module in binwalk.scan('dlink_DCS_930L.bin', signature=True, quiet=True, matryoshka=True, extract=True):`

**Comment by HassamK97** [comment]
Thanks, Issue resolved.

**Comment by HassamK97** [comment]
> Use
> `for module in binwalk.scan('dlink_DCS_930L.bin', signature=True, quiet=True, matryoshka=True, extract=True):`

Thanks, issue resolved.
