### ISSUE TITLE
how can i decrypt huawei HG531s v1 config file?

### ISSUE THREAD

**Issue by minanagehsalalma** [ReFirmLabs/binwalk#419]
[I have tried to follow this guide](https://hg658c.wordpress.com/2017/12/04/decrypting-configuration-files-from-other-huawei-home-gateway-routers/) but libxmlapi.so didn't have the required ATP_GetInfo1 function so i moved to the next file libhttpapi.so it had
```
ATP_GetInfo1
ATP_GetInfo2 
ATP_GetInfo3 
ATP_GetInfo4
```
so i copied the first two .

then ATP_GetInfo3 from libcfmapi.so file

then ATP_GetInfo4 from libmsgapi.so file .... and when i tried to run the script decode_keystore.py but it gave me

> ValueError: Input strings must be a multiple of 16 in length

.... and i think because the values wasn't in the same length

[The firmware file
](https://www.mediafire.com/file/4x8y97j256uvd04/hg531s1.BIN/file)

**Comment by CoffeeExpress** [comment]
Binwalk doesn't support the encryption used by this firmware file.

**Comment by minanagehsalalma** [comment]
@CoffeeExpress  do you mean it can't extract the files from the bin file or you mean that  it can't decrypt the config file ? 
Cause i was able to extract the files using 7 zip but got an error at the end 
![image](https://user-images.githubusercontent.com/20546638/61007817-212f7880-a36e-11e9-9efa-7ceae689547c.png)
![image](https://user-images.githubusercontent.com/20546638/61007833-28ef1d00-a36e-11e9-9eb7-75cbb3f52aaa.png)
and there wasn't a much missing files tho .

**Comment by CoffeeExpress** [comment]
It can't decrypt the config file.

**Comment by minanagehsalalma** [comment]
@CoffeeExpress  what do suggest cause i really need to decrypt that file and i have asked on a lot of sites and no one did really help !

**Comment by vido89** [comment]
Download aescrypt2 and try aescrypt2_huawei.exe

**Comment by minanagehsalalma** [comment]
@vido89  i have already tried it and it didn't work 
from the README file it says 
> These models have hw_ctree.xml file:
> 
> hg55x hg612 hg8010 hg8010c92 hg8040 hg8040f hg8045 hg8045v2 hg8110 hg8110c92
> hg8120 hg8120c92 hg8120r hg8120rc92 hg8240 hg8240c93 hg8240f hg8240fcig
> hg8240j hg8240p hg8240r hg8240rc93 hg8240rva hg8240s hg8240t hg8240w hg8242
> hg8242b hg8244t hg8245 hg8245c93 hg8245f hg8245r hg8245t hg8247 hg8247a
> hg8247t hg8447
> 
and in fact the config file that i want to decrypt is .bin

**Comment by minanagehsalalma** [comment]
> aescrypt2_huawei.exe 1 defaultcfg.xml 1.xml
> version header of file wrong!
> 
> Press <Enter> to exit.
>

**Comment by whhw31** [comment]
Were you able to figure this out, I'm doing this as a project and i hit a dead end, i was able to binwalk and extract squeshfs and edit for root access on uart and ssh but when the router boots there is a checksum error, probably the bootloader checking the squashfs before decompressing it, and the bootloader part is encrypted

**Comment by minanagehsalalma** [comment]
@whhw31 

> and the bootloader part is encrypted

you could simply read it when it's loaded into memory ... stuff gets decrypted in that state.

these [may be of help](https://www.pentestpartners.com/security-blog/how-to-do-firmware-analysis-tools-tips-and-tricks/) ... the part about encrypted bin files. 

these too 

https://www.zerodayinitiative.com/blog/2020/2/6/mindshare-dealing-with-encrypted-router-firmware

https://watchfulip.github.io/28-12-24/tp-link_c210_v2.html

**Comment by whhw31** [comment]
I don't know a way to read the memory from the device, the  bootloader menu is very limited, or may be you mean by simulation.
