### ISSUE TITLE
how can i Encrypt zte zxhn h108n V2.5 config file?

### ISSUE THREAD

**Issue by minanagehsalalma** [ReFirmLabs/binwalk#420]
i was able to Decrypt the the config file using [nirsoft tool router pass view](https://www.nirsoft.net/utils/router_password_recovery.html)

but there was no encrypting option so i can upload the file again to the router !

**Comment by CoffeeExpress** [comment]
Unfortunately, I don't think is a binwalk related question, so I'm going to close it.

**Comment by minanagehsalalma** [comment]
@CoffeeExpress  which Repo do you think that it's related to  ?

**Comment by CoffeeExpress** [comment]
You might try contacting the creator the Router Pass View to see if he has any suggestions - nirsofer@yahoo.com

**Comment by minanagehsalalma** [comment]
@CoffeeExpress  i have already did and he barely replied but he seemed ignored this part about the encrypting .
