### ISSUE TITLE
extracted jffs2 folder is empty

### ISSUE THREAD

**Issue by DMirror** [ReFirmLabs/binwalk#431]
I am using Binwalk v2.2.0-be738a5 and I installed jefferson with all dependencies.

When I analyze the dump that I extracted from a NAND Flash I get:
```
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
1             0x1             uImage header, header size: 64 bytes, header CRC: 0x9ACE133A, created: 2016-03-04 02:44:23, image size: 1246173 bytes, Data Address: 0x80060000, Entry Point: 0x80060000, data CRC: 0xA355CA8A, OS: Linux, CPU: MIPS, image type: OS Kernel Image, compression type: lzma, image name: "MIPS OpenWrt Linux-3.14"
2064029       0x1F7E9D        UBI erase count header, version: 1, EC: 0x1, VID header offset: 0x800, data offset: 0x1000
2706593       0x294CA1        xz compressed data
6653505       0x658641        xz compressed data
6781227       0x67792B        xz compressed data
6915374       0x69852E        xz compressed data
7443102       0x71929E        xz compressed data
11576127      0xB0A33F        JFFS2 filesystem, big endian
11706805      0xB2A1B5        JFFS2 filesystem, big endian
```
I tried to extract all the files with `binwalk -Me filename`.

Binwalk created a new folder on my Desktop with all the files that you can see in the output above but there are two empty folders that should contain the files that are part of the filesystem. I tried to extract the content of two other images that I found online. One contained a little endian JFFS2 fs. That worked fine. The other one contained a big endian fs and I had the same issue.
Is this an endianness problem and if yes is there a way I can work around the problem?

**Comment by nwrkbiz** [comment]
Do you have jefferson installed? (https://github.com/sviehb/jefferson)
If no install it and try again.
