### ISSUE TITLE
Unexpected keyword: "depth"

### ISSUE THREAD

**Issue by 0xfede7c8** [ReFirmLabs/binwalk#436]
```python
 extracted_elements = self.binwalker.extract(path, depth=8)
745 TypeError: extract() got an unexpected keyword argument 'depth'
````

Did you happen to remove `depth` parameter from the API?

**Comment by devttys0** [comment]
It is a supported parameter, which may be passed to `binwalk.scan`: https://github.com/ReFirmLabs/binwalk/wiki/Scripting-With-the-Python-API
