### ISSUE TITLE
Extraction hangs when extracting an encrypted zip

### ISSUE THREAD

**Issue by targodan** [ReFirmLabs/binwalk#443]
The error from #108 seems to be back. When extracting encrypted zip file binwalk hangs without any output. Happened to me when walking through wannacry as contained in theZoo.

You can get around this problem by adding the `-z` parameter but either a password prompt or aborting the extraction automatically would be nice.

**Comment by pmarrapese** [comment]
Found a workaround: `unzip` supports passing options via environment variables, so you can specify the password with something like ` UNZIP='-p mypassword' binwalk -Mre encrypted.bin`

**Comment by devttys0** [comment]
Should be fixed now: https://github.com/ReFirmLabs/binwalk/blob/6f64ba30b06a021ab60aca35e720bb4f8ce72ba5/src/binwalk/config/extract.conf#L57
