### ISSUE TITLE
Linux Kernel Version to Reduce False Positives

### ISSUE THREAD

**Issue by eacmen** [ReFirmLabs/binwalk#471]
https://github.com/ReFirmLabs/binwalk/blob/a4945a93ef85af89ccf99a212ea5205c6e749b5c/src/binwalk/magic/linux#L13

Bug report from Centrifuge user. This signature seems to generate a fair amount of false positives. Is it possible to reduce these false positives? Any other bytes surrounding the version string that would only appear in a kernel?

**Comment by devttys0** [comment]
Binwalkv3 has improved (but still imperfect) Linux kernel version signaturing.
