### ISSUE TITLE
REQUEST: TP-Link RE300/RE305 Header is not read correctly

### ISSUE THREAD

**Issue by rmcbc** [ReFirmLabs/binwalk#474]
First of all thanks for your excellent work.

Sorry for disturbing you with this, but Is it possible to add to Binwalk the TP-Link RE300/RE305 firmware header correct format?

Actual result with "master" branch:

```
DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
87636         0x15654         U-Boot version string, "U-Boot 1.1.3 (Nov 14 2019 - 08:47:01)"
106477        0x19FED         TP-Link firmware header, firmware version: 0.0.0, image version: "", product ID: 0x0, product version: 0, kernel load address: 0x0, kernel entry point: 0x80, kernel offset: 0, kernel length: 512, rootfs offset: 878546, rootfs length: 0, bootloader offset: 0, bootloader length: 0
106989        0x1A1ED         LZMA compressed data, properties: 0x5D, dictionary size: 33554432 bytes, uncompressed size: 2536732 bytes
985536        0xF09C0         Squashfs filesystem, little endian, version 4.0, compression:xz, size: 6774884 bytes, 1380 inodes, blocksize: 1048576 bytes, created: 2019-11-14 01:35:40
```
I saw some one describing the header format for RE450 [here](https://git.mr-cn.net/mr/openwrt/commit/0d9d980ecd6fce5708003ed16c3238a680b1b16e) I don't know if it helps.

**Comment by devttys0** [comment]
I've taken a look at the RE300/305 firmware, unfortunately there doesn't appear to be any reliable/repeatable data at the beginning of the firmware images to signature on. I suspect it's just a raw u-Boot bootloader, but have not confirmed.
