### ISSUE TITLE
Installation problem of binwalk under ubuntu18.04

### ISSUE THREAD

**Issue by houtu** [ReFirmLabs/binwalk#475]
mkcramfs.c: In function ‘interpret_table_entry’:
mkcramfs.c:1263:5: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
     asprintf(&buf, "%s%lu", name, i);
     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
gcc -W -Wall -O2 -g -I.   cramfsck.c  -lz -o cramfsck
cramfsck.c: In function ‘test_crc’:
cramfsck.c:229:4: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
    read(fd, buf, super.size);
    ^~~~~~~~~~~~~~~~~~~~~~~~~
cramfsck.c: In function ‘romfs_read’:
cramfsck.c:299:3: warning: ignoring return value of ‘read’, declared with attribute warn_unused_result [-Wunused-result]
   read(fd, read_buffer, ROMBUFFERSIZE * 2);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
cramfsck.c: In function ‘do_symlink’:
cramfsck.c:633:3: warning: ignoring return value of ‘asprintf’, declared with attribute warn_unused_result [-Wunused-result]
   asprintf(&str, "%s -> %s", path, outbuffer);
   ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

**Comment by devttys0** [comment]
These appear to only be warnings, not errors; also, these are external tools that binwalk uses for extracting CramFS filesystems (I assume these warnings occurred while running `deps.sh`), but they are not part of binwalk itself and should be reported to their respective project owners.

These warnings should not prevent these tools from building/installing, and should definitely not prevent binwalk itself from installing.
