### ISSUE TITLE
strlen limitation breaks non-NULL-terminated strings

### ISSUE THREAD

**Issue by biot** [ReFirmLabs/binwalk#483]
The U-Boot image header has as its last field the image name, a string of up to 32 bytes, but it's not necessarily NULL-terminated. If the name is longer than 32 bytes, mkimage chops it off at 32 and puts that in there, with no guarantee that the name is NULL-terminated. In fact this happens often, for example in case there's a git commit hash in the filename. Attached is a real-world example.

When binwalk comes across this, the magic fails to work. I've tried to fix up the signature by adding {strlen:32} and {string}, but that fixes it to 32 bytes -- and break shorter strings in that field. There is no size field to use -- it's 32 bytes or less, and NULL-terminated if less.

Is there a way to fix this signature with current facilities, or does this need a new "maxstrlen" (or whatever) directive?

[u-boot.img.zip](https://github.com/ReFirmLabs/binwalk/files/5125986/u-boot.img.zip)

**Comment by devttys0** [comment]
I just pushed a fix for this, thanks for the catch! FWIW, I just updated the format string in the uImage signature to limit the string to 32 bytes like this:

```>32    string    x              image name: "%.32s"```

For NULL terminated strings that are less than 32 bytes, the string is cut off at the first NULL.
