### ISSUE TITLE
binwalk invoked oom-killer

### ISSUE THREAD

**Issue by ricardodeazambuja** [ReFirmLabs/binwalk#503]
I'm trying to recover data from a sd card image that got corrupted (~15GB) using `binwalk -e image.img`, but it eats all the memory (32GB!) and the OS finally kills it (oom-killer). I tested limiting the memory `systemd-run --scope -p MemoryMax=5G binwalk -e image.img` and it is killed when it reaches the maximum (5G in this case). When I simply print signatures on the screen, it doesn't crash (CPU usage hits 100% while memory stays below 1%).

**Comment by akx** [comment]
Have you tried e.g. Testdisk or Photorec instead?

**Comment by ricardodeazambuja** [comment]
Thanks!!! Testdisk solved all my problems.
