### ISSUE TITLE
Can't not extract file with extension cpio.gz

### ISSUE THREAD

**Issue by newthis** [ReFirmLabs/binwalk#504]
Hi, I recently use binwalk to extract file from a file with extension cpio.gz.
However, I find that the extraction result is incorrect.
The file link is here:

**https://github.com/newthis/extraction_error/raw/master/rootfs.cpio.gz**

The binwalk does not extract the file system in it correctly, however, the 7z tool can 
extract it correctly.

**Comment by SambasOnFire** [comment]
Here it extracts without problems!
cmd @binwalk -Me -r rootfs.cpio.gz

**Comment by newthis** [comment]
@SambasOnFire ，could you tell me what is the version of binwalk for testing? I give a try again.

**Comment by SambasOnFire** [comment]
Binwalk v2.1.2

**Comment by devttys0** [comment]
This extracts ok in Binwalk v3
