### ISSUE TITLE
DepreactionWarning: the imp module is deprecated in favour of importlib

### ISSUE THREAD

**Issue by mapreri** [ReFirmLabs/binwalk#507]
Hi,

the `imp` module has been deprecated since Python 3.4.  Please consider moving to importlib.

```
/usr/lib/python3/dist-packages/binwalk/core/plugin.py:4

  /usr/lib/python3/dist-packages/binwalk/core/plugin.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
    import imp
```

**Comment by swt2c** [comment]
`imp` has now been removed in Python 3.12.

**Comment by mzpqnxow** [comment]
See https://github.com/ReFirmLabs/binwalk/commit/3e5c6887e840643fdbe7358de4bb31d726d0ce1b for one way to fix this and keep backwords compatibility
