### ISSUE TITLE
Also print block length

### ISSUE THREAD

**Issue by mrx23dot** [ReFirmLabs/binwalk#514]
Currently it prints:

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------
1632990       0x18EADE        Zip archive data, at least v2.0 to extract, compressed size: 18542, uncompressed size: 173427, name: dummy.xml

Please also add **LENGTH column,** which doesn't depend on content type, it would help post processing individually.
(mentioned size doesn't include zip header, thus not raw length)

eg:
DECIMAL       HEXADECIMAL  LEN   DESCRIPTION
--------------------------------------------------------------------------------
1632990       0x18EADE    2000    Zip archive data, at least v2.0 to extract, compressed size: 18542, uncompressed size: 173427, name: dummy.xml

**Comment by eacmen** [comment]
Length isn't always known for every binwalk signature as such this issue cannot be implemented.
