### ISSUE TITLE
PyQtGraph Maintainer - We Are Updating Dependency Requirements; which may affect you.

### ISSUE THREAD

**Issue by j9ac9k** [ReFirmLabs/binwalk#515]
Hello binwalk maintainers, pyqtgraph maintainer here.

@swt2c was kind enough to give me a heads up on some errors pyqtgraph had with respect to Python 3.10, and mentioned this library using pyqtgraph.

As of 0.12.0 (which is coming up right around the corner) we on support Qt 5.12+ and python 3.7+, and numpy 1.17+.  We do support Qt6 as well (but not PyQt6 6.0.0, they already released 6.0.1 which we fully support).  Looking at `INSTALL.md` it looks like these changes will be impacting you, so I thought I would give you a heads up.

Also if there are any pyqtgraph specific issues impacting your library, I'd love to hear about them.

**Comment by eacmen** [comment]
Thanks for the heads up. We will keep an eye on it. I think our recent updates will alleviate this issue as we are ditching support for 2.7.
