### ISSUE TITLE
Chi Square Distribution & Pi Approximation Error

### ISSUE THREAD

**Issue by figbux** [ReFirmLabs/binwalk#535]
Hello,

What happened to these heuristics mentioned in http://www.devttys0.com/2013/06/differentiate-encryption-from-compression-using-math/?

**Comment by devttys0** [comment]
This was eventually removed, but the code is still available in older releases: https://github.com/ReFirmLabs/binwalk/releases/tag/v2.1.1

See the binwalk-2.1.1/src/binwalk/modules/heuristics.py file.
