### ISSUE TITLE
python: can't open file 'C:\Python27\Scripts\binwalk': [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by retr0cube** [ReFirmLabs/binwalk#545]
Hi !

I installed Binwalk from this repo but  every time when i run `binwalk my_file.bin every time I get this error :

`python: can't open file 'C:\Python27\Scripts\binwalk': [Errno 2] No such file or directory`

Any help is appreciated !

**Comment by kushkaizer** [comment]
Hi has anyone been able to solve this problem yet?

**Comment by ek-nath** [comment]
I think, generally speaking, you should upgrade the python interpreter from 2.7 to 3.x. There's a note in the main readme as well.

**Comment by Shengpy** [comment]
you should open binwalk.py and change the directory where (......\\binwalk-master\\src\\binwalk)  binwalk-master located, then  you open ...\binwalk-master\src\binwalk\modules\extractor.py  and comment all the line have pwd ( #import pwd ), finally binwalk.py will run easily
