### ISSUE TITLE
Can't use binwalk

### ISSUE THREAD

**Issue by vunhatchuong123** [ReFirmLabs/binwalk#547]
When I try to use binwalk or python binwalk on cmd. It tells me to choose a program to open

**Comment by megapro17** [comment]
This shit isn't working in windows

**Comment by v-micada** [comment]
**According to the documentation, Binwalk is only experimental on Windows:**
https://github.com/ReFirmLabs/binwalk/wiki/Frequently-Asked-Questions#does-binwalk-work-on-windows
https://github.com/ReFirmLabs/binwalk/wiki/Supported-Platforms
 
**You can try running Binwalk from Cygwin on Windows instead:**
https://github.com/ReFirmLabs/binwalk/wiki/Supported-Platforms
https://www.cygwin.com/

Another option would be to use a Binwalk docker image on Windows.

**Comment by stoney84** [comment]
try cmd

**Comment by Bamgm14** [comment]
Doesn't work
Revert to Binwalk 2.3.2 and it should be fine
Adding pwd was what caused this
