### ISSUE TITLE
pwd and os incompatibility

### ISSUE THREAD

**Issue by Bamgm14** [ReFirmLabs/binwalk#562]
Hey, so been awhile, just noticed that added new features and also broke windows compatibility again XD
I am looking at ways to fix it myself but just a heads up!

**Comment by Bamgm14** [comment]
Also, to all Windows Brothers 
Use the Linux subsystem till then

**Comment by haiqu** [comment]
Yah, 2.3.2 works, 2.3.3 got broken with pwd.

**Comment by Bamgm14** [comment]
Been looking for a bypass but there aren't any direct analogues
Atleast none I can find
Any suggestions on where to look
