### ISSUE TITLE
WebP support?

### ISSUE THREAD

**Issue by mhombach** [ReFirmLabs/binwalk#592]
I was wondering if binwalk already supports finding `webp` files in a dump/bin and if not, if that would be something easy to be implemented :)

**Comment by mzpqnxow** [comment]
Type “webp” into the github search box for this project, that will probably answer your first question 

I can’t speak to the second, but generally speaking if webp files have a “magic” and/or well-known header, then no, it’s not terribly difficult. Though you may have noticed this repository is no longer maintained so you’re on your own (see Binwalk pro)

**Comment by devttys0** [comment]
Binwalk v3 now supports WebP image detection and extraction:

![image_2024-09-23_120422402](https://github.com/user-attachments/assets/21febeb5-700b-429e-ac96-0ace9d876e49)
