### ISSUE TITLE
ubi filesystem extraction

### ISSUE THREAD

**Issue by MatthewTingum** [ReFirmLabs/binwalk#596]
From what I can tell, binwalk doesn't support extraction of `ubi` filesystems.

I'm not certain if there's a magic that can be used to detect them.
There are python tools that can be used to extract ubi files such as [ubidump](https://github.com/nlitsme/ubidump)

What would it take to include such a tool?

I know that third party tools are sometimes used in extraction.
sasquatch comes to mind.

Sometimes these third party tools have to be manually installed.
Ever thought about pulling them in as submodules?

**Comment by mzpqnxow** [comment]
I will push the changes I made to my fork when I have time, or you can make them yourself

Add an `extractor` method to the class @  https://github.com/ReFirmLabs/binwalk/blob/master/src/binwalk/plugins/ubivalid.py 

Have it use the ubifs tools. Follow the [cpio plugin](https://github.com/ReFirmLabs/binwalk/blob/master/src/binwalk/plugins/ubivalid.py) as a guide

If I remember correctly the command I used for the extraction in that method was `ubi_image_extract`

**Comment by devttys0** [comment]
UBI is supported in Binwalk v3:

![image_2024-09-22_211658031](https://github.com/user-attachments/assets/68447d07-750d-44ec-8501-0ca1afc17e81)
