### ISSUE TITLE
kali 2022.1 (unsquashfs.c error) -Werror=misleading-indentation

### ISSUE THREAD

**Issue by ghost** [ReFirmLabs/binwalk#598]
hi guys, I try to install sasquatch to extract non-standard SquashFS images and getting this error on kali 2022.1 
what can I do to solve this issue ? I have latest binwalk installed. 

![image](https://user-images.githubusercontent.com/48986997/162840187-3cfda0dd-1e84-4d30-a42c-de5e059b10ff.png)

**Comment by ffontaine** [comment]
`deps.sh` must be updated to apply the following patch on sasquatch: https://github.com/devttys0/sasquatch/pull/47
