### ISSUE TITLE
pkg_resources.ResolutionError: Script 'scripts/binwalk' not found in metadata at None

### ISSUE THREAD

**Issue by haowayne** [ReFirmLabs/binwalk#607]
Hi. I followed the Installation, running the deps.sh and setup.py in Ubuntu18.04 . But I didn't launch binwalk correctly. Could you help me ? Here are my installation info and python info.  (PS: Before I installed binwalk, I had compiled and installed python3.8 and used update-alternatives to change python3.8 as default  instead of python3.6)

installation
![2PHTMBNUFX0(LYV~7EL6V%T](https://user-images.githubusercontent.com/22594554/183406344-70faee37-2273-4728-95ee-510caa910b60.png)
![YUH~MBP0@6AYTYDY_QSJCI6](https://user-images.githubusercontent.com/22594554/183406365-82b66fc1-245f-478e-9fdb-625900191c12.png)

launch binwalk error 
![A59HS`}XTG0WBLNTM_9Y7_K](https://user-images.githubusercontent.com/22594554/183406399-e3088687-f15c-4116-996d-73fe692b736e.png)

**Comment by tnt944445** [comment]
Hey, could you elaborate on how you resolved this issue? I'm having the same issue on Ubuntu 18.04.6
