### ISSUE TITLE
Porting/Cross-compile/Build binwalk for Windows

### ISSUE THREAD

**Issue by jowinjohnchemban** [ReFirmLabs/binwalk#612]
I'm thinking about Porting/Cross-compile/Build binwalk for Windows

https://github.com/jowinjohnchemban/winbinwalk

I had created a hack to run binwalk in Windows, years ago.

Now planning to take it to the next level
Anyone here wish to join the effort Welcome

**Comment by akx** [comment]
FWIW, my PR https://github.com/ReFirmLabs/binwalk/pull/454 implements Windows compatibility.
