### ISSUE TITLE
Uncorrect work with key "-Y"

### ISSUE THREAD

**Issue by vovabush** [ReFirmLabs/binwalk#616]
There are file (packed): [auth.zip](https://github.com/ReFirmLabs/binwalk/files/9868243/auth.zip)

Binwalk with key "-Y" say this ARM big endian architecture, but realy it is MIRS architecture. 

![image](https://user-images.githubusercontent.com/3701803/197995137-26290ce8-a236-4210-8f35-ac488f884147.png)

**Comment by seifallahhomrani1** [comment]
I faced the same issue unless you increment the minimum number of consecutive instructions. 
@vovabush you can use readelf and extract the correct architecture instead.
