### ISSUE TITLE
can't get this resource

### ISSUE THREAD

**Issue by bio-zj** [ReFirmLabs/binwalk#619]
when I run ./deps.sh, I can't get the resource called"stuffit520.611linux-i386.tar.gz", and the link is disabled!!!!
![屏幕截图 2022-11-06 003403](https://user-images.githubusercontent.com/69226513/200131267-ce385649-4756-44a1-95eb-7bfd7a292bf2.png)

**Comment by patel-aum** [comment]
http://mirror.sobukus.de/files/grimoire/z-archive/stuffit520.611linux-i386.tar.gz
