### ISSUE TITLE
No module named 'binwalk.__main__'

### ISSUE THREAD

**Issue by Randark-JMT** [ReFirmLabs/binwalk#638]
I tried installing directly from the source and also sudo apt install binwalk, all with this error

```shell
$ binwalk
Traceback (most recent call last):
  File "/usr/bin/binwalk", line 2, in <module>
    from binwalk.__main__ import main
ModuleNotFoundError: No module named 'binwalk.__main__'
```

**Comment by 7h4nd5RG0d** [comment]
was this resolved?

**Comment by Randark-JMT** [comment]
Oh about that, I haven't encountered that problem since I switched from kali to parrot later on, thank you very much for your interest in this issue!
