### ISSUE TITLE
ubireader problem

### ISSUE THREAD

**Issue by urn1ce** [ReFirmLabs/binwalk#651]
https://github.com/jrspruitt/ubi_reader doesn't have setup.py, but in https://github.com/ReFirmLabs/binwalk/blob/master/deps.sh still use setup.py
function install_ubireader
{
    git clone --quiet --depth 1 --branch "master" https://github.com/jrspruitt/ubi_reader
    (cd ubi_reader && $SUDO $PYTHON setup.py install)
    $SUDO rm -rf ubi_reader
}

**Comment by urn1ce** [comment]
https://github.com/ReFirmLabs/binwalk/blob/master/INSTALL.md also have this problem

**Comment by nhtri2003gmail** [comment]
Hi, I see this link seems useful: https://github.com/ReFirmLabs/binwalk/issues/642#issuecomment-1567514863

**Comment by urn1ce** [comment]
> Hi, I see this link seems useful: [#642 (comment)](https://github.com/ReFirmLabs/binwalk/issues/642#issuecomment-1567514863)

This is very useful, but I still hope that the official team will fix it.

**Comment by dierye** [comment]
That's because ubi_reader use a new branch name "main".If you don't want to change a lot , you can easily change the branch param to "v0.8.5-master".

**Comment by kdelson** [comment]
Agree, this should be a pretty simple fix but it appears the ubi_reader team have migrated to poetry so anything relying on the old setup script is broken in latest.

**Comment by ojuanjo** [comment]
When I changed the command in the sh file, he had a new problem:

Processing ./ubi_reader
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... done
ERROR: Could not find a version that satisfies the requirement lzallright<0.3.0,>=0.2.1 (from ubi-reader) (from versions: none)
ERROR: No matching distribution found for lzallright<0.3.0,>=0.2.1
