### ISSUE TITLE
Dockerfile fails to build due to ubi_reader changes

### ISSUE THREAD

**Issue by whoami-defnotme** [ReFirmLabs/binwalk#658]
I received build errors while trying to build an image using the current Dockerfile in this repo.

[ubi_reader](https://github.com/onekey-sec/ubi_reader) now uses `main` as the default branch instead of `master` and no longer uses a `setup.py` file.

I was able to change [this function in deps.sh](https://github.com/ReFirmLabs/binwalk/blob/cddfede795971045d99422bd7a9676c8803ec5ee/deps.sh#L116) to simply use the following command (recommended from [ubi_reader](https://github.com/onekey-sec/ubi_reader#installation) and was able to successfully build the Docker image:

```
install_pip_package "ubi_reader"
```

I'm not sure if this is the code change you want or if you'd rather change the `install_ubireader` to directly install from source so I'm just raising this as an issue instead of providing this as a PR.

**Comment by vincejv** [comment]
thanks for this! was able to run binwalk successfully from docker, i hope the maintainers have the time to update the code
