### ISSUE TITLE
deprecated nose dependency, deprecated used of setup.py test

### ISSUE THREAD

**Issue by xambroz** [ReFirmLabs/binwalk#665]
Hello,
please consider switching from nose to pytest or nose2.

The binwalk tests depend on long deprecated python module nose. 
In Fedora it is so far only deprecated (since 2020), but for example it is already missing from RHEL9. 

Relevant info:
https://nose.readthedocs.io/en/latest/ - in maintenance mode for several years, recommends users to switch to nose2 or pytest
https://fedoraproject.org/wiki/Changes/DeprecateNose

Same applies for using the "setup.py test" directly.
https://packaging.python.org/en/latest/discussions/setup-py-deprecated/#:~:text=However%2C%20python%20setup.py%20and,python%20setup.py%20develop

Thank you
Michal Ambroz

**Comment by a-detiste** [comment]
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1018315
