### ISSUE TITLE
[Feature Request] Extract RSA/Certificates and Private Keys

### ISSUE THREAD

**Issue by OdinVex** [ReFirmLabs/binwalk#677]
The ability to scan and extract certificates would be nice, such as:
```
-----BEGIN CERTIFICATE-----
<BASE64 AND CRLFS ONLY>
-----END CERTIFICATE-----
```
and
```
-----BEGIN RSA PRIVATE KEY-----
<BASE64 AND CRLFS ONLY>
-----END RSA PRIVATE KEY-----
```

**Comment by devttys0** [comment]
Good news, Binwalk v3 does exactly that :)

![image_2024-09-22_213507595](https://github.com/user-attachments/assets/f1ef0013-d5c5-443f-b16f-d48d407d00c9)
