### ISSUE TITLE
The command line did not report an error, but did not unpack any files

### ISSUE THREAD

**Issue by yaaaaaao** [ReFirmLabs/binwalk#678]
Hello, I am trying to unpack some files with Binwalk, such as a sample elf suffix, I ran the package command "binwalk --extract -M --directory /home/lius/results-/home/lius/esp32-app-template.elf "with no error. But the result doesn't have any files in it. I need some help.

**Comment by devttys0** [comment]
Binwalk v3 does correctly identify this file as an ELF, and also reports some possible SHA256 hash constants in the ELF file as well:

![image_2024-09-22_212943599](https://github.com/user-attachments/assets/e1e4bff7-083e-48c4-9b25-bb5612d355d9)

With that said, there doesn't seem to be anything to "extract" here. It's an ELF executable; if you want to understand how it works, you'll want to open it up in a disassembler or decompiler.
