### ISSUE TITLE
getting a lot of errors

### ISSUE THREAD

**Issue by amagmu** [ReFirmLabs/binwalk#68]
Unable to use this version of binwalk. Getting those errors:
WARNING: Error loading plugin 'lzmamod.py': [Errno 13] Permission denied
The files concerned are: 
'zlibvalid.py'
'tar.py'
'cpio.py'
'lzmamod.py'
'compressd.py'

**Comment by fritzw** [comment]
It seems that this problem still exists. It happens on Ubuntu Ubuntu 14.04.4 LTS, both when installed via `pip install binwalk` and when running `sudo python setup.py install` from the downloaded tarball from github.

This is what the plugins folder looks like after installation. Note that I am not in the staff group.

```
$ ll /usr/local/lib/python2.7/dist-packages/binwalk/plugins/
total 120K
-rw-r----- 1 root staff 2,7K Dez 23  2015 arcadyan.py
-rw-r--r-- 1 root staff 2,5K Aug 11 14:48 arcadyan.pyc
-rw-r----- 1 root staff 1,4K Dez 23  2015 compressd.py
-rw-r--r-- 1 root staff  502 Aug 11 14:48 compressd.pyc
-rw-r----- 1 root staff 3,9K Dez 23  2015 cpio.py
-rw-r--r-- 1 root staff 2,9K Aug 11 14:48 cpio.pyc
-rw-r----- 1 root staff 1,5K Dez 23  2015 gzipextract.py
-rw-r--r-- 1 root staff 1,7K Aug 11 14:48 gzipextract.pyc
-rw-r----- 1 root staff 1,8K Dez 23  2015 gzipvalid.py
-rw-r--r-- 1 root staff 1,7K Aug 11 14:48 gzipvalid.pyc
...
```
