### ISSUE TITLE
Warnings after run python3 install on macOS

### ISSUE THREAD

**Issue by DK-DARKmatter** [ReFirmLabs/binwalk#682]
My python version is 3.9.6. Get following warning and cannot continue:
/Library/Python/3.9/site-packages/binwalk-2.3.3-py3.9.egg/binwalk/modules/extractor.py:969: SyntaxWarning: "is" with a literal. Did you mean "=="?
/Library/Python/3.9/site-packages/binwalk-2.3.3-py3.9.egg/binwalk/modules/extractor.py:984: SyntaxWarning: "is" with a literal. Did you mean "=="?
/Library/Python/3.9/site-packages/binwalk-2.3.3-py3.9.egg/binwalk/modules/extractor.py:969: SyntaxWarning: "is" with a literal. Did you mean "=="?
/Library/Python/3.9/site-packages/binwalk-2.3.3-py3.9.egg/binwalk/modules/extractor.py:984: SyntaxWarning: "is" with a literal. Did you mean "=="?

**Comment by devttys0** [comment]
The Python version of Binwalk is largely unmaintained and will soon be depreciated. It is succeeded by Binwalk v3, which is written in Rust; unfortunately, at least for now, only Linux is supported
