### ISSUE TITLE
request a new release

### ISSUE THREAD

**Issue by chenrui333** [ReFirmLabs/binwalk#691]
mostly followup https://github.com/ReFirmLabs/binwalk/issues/671, thanks!!

The new release would also help shipping this commit, https://github.com/ReFirmLabs/binwalk/commit/3e5c6887e840643fdbe7358de4bb31d726d0ce1b

**Comment by devttys0** [comment]
Shooting for a stable v3 release by the end of October. :)

**Comment by devttys0** [comment]
v3 released!

https://github.com/ReFirmLabs/binwalk/releases/tag/v3.1.0
