### ISSUE TITLE
LZMA compressed data, properties: 0x5D, dictionary size

### ISSUE THREAD

**Issue by Baturax** [ReFirmLabs/binwalk#694]
10292         0x2834          LZMA compressed data, properties: 0x5D, dictionary size: 8388608 bytes, uncompressed size: 2793336 bytes
here is firmware: https://www.mediafire.com/file/9cx0nwnf4ouh8qf/modem.bin/file

**Comment by devttys0** [comment]
The LZMA result reported by Binwalk is valid and decompresses properly, so I assume that you expected to find more than just a compressed LZMA blob, such as perhaps a file system. In this case, there is no proper file system in the firmware and the reported LZMA blob is really the only thing in the firmware to extract.

Here's my quick analysis of the firmware:

The file size is 872Kb, much too small for a Linux-based firmware, so we're probably dealing with an RTOS.

Running `binwalk -Me modem.bin` produces:

![image_2024-10-14_084425112](https://github.com/user-attachments/assets/8923404f-dd05-455f-9b46-c244c33849a3)

The LZMA data from modem.bin is extracted and decompressed, and Binwalk reports that the decompressed data contains an [eCos](https://en.wikipedia.org/wiki/ECos) exception handlers for big-endian MIPS. There are also some image files embedded into the decompressed data, likely for use in the modem's Web-based administrative interface.

Looking at the strings in the `decompressed.bin` file reveals several references to eCos, so this is almost certainly an eCos kernel:

![image_2024-10-14_085008008](https://github.com/user-attachments/assets/f23b41bc-8c63-4461-83a1-b136fc53a587)

[cpu_rec](https://github.com/trou/cpu_rec_rs) also confirms that the `decompressed.bin` file contains MIPS instructions:

![image](https://github.com/user-attachments/assets/2f535e49-4766-4229-9801-74ae758a071c)

This all looks pretty normal for an eCos kernel, so the question is: did Binwalk miss anything important in the original `modem.bin` file?

Binwalk reports that the LZMA data in `modem.bin` starts at offset 10292 and that the compressed LZMA data is 879759 bytes long; 10292 + 879759 = 890051, but the `modem.bin` file is 892928 bytes in size. This means that there is some other data at the end of the file.

Looking at a hex dump of `modem.bin`, we can see that there is some extra data that comes after the LZMA blob at the end of the file, but it's mostly NULL bytes, probably nothing of importance:

![image](https://github.com/user-attachments/assets/df008df9-ad61-4529-8e7f-e1fe62d73a92)

Ok, what about the beginning of the file? 

![image](https://github.com/user-attachments/assets/b716b8ca-a983-40cd-95f7-460ca64ef83f)

The first four bytes (`RTK0`) are probably "magic" bytes to identify the firmware image. The next four bytes, interpreted as little endian, are 0x000da000, or 892928 in decimal; this is the size of the `modem.bin` file. So this is some sort of header information.

Again using cpu_rec, we can see that the beginning of the `modem.bin` file appears to be mostly MIPS executable code:

![image](https://github.com/user-attachments/assets/6d042b15-d1b1-4332-8009-5bd8256c7774)

And looking at the hex dump of this MIPS code shows some strings that suggest it is likely a small bootloader/decompression stub repsonsible for decompressing the LZMA compressed eCos kernel and loading it into memory:

![image](https://github.com/user-attachments/assets/8e760175-4ec4-4996-85f0-93fbc793c8c5)

Further analysis of this firmware would require loading the eCos kernel into a disassembler/decompiler and reverse engineering the code.

The only other thing Binwalk could possibly assist with would be identifying and reporting the `RTK0` firmware header; I'll take a closer look at it when I have some cycles and write a signature for it, though it will probably be of limited assistance in further analyzing this firmware.

**Comment by devttys0** [comment]
Update: I've added the RTK firmware header signature to Binwalkv3:

![image](https://github.com/user-attachments/assets/1eb768f2-d509-4ea7-beb3-5171cd249ce1)
