### ISSUE TITLE
Add support for NTFS Fillesystem

### ISSUE THREAD

**Issue by shiren00** [ReFirmLabs/binwalk#713]
We would appreciate it if anyone with additional materials or actual disk image files related to this could share them :D
tsk_recover supports this.

- https://learn.microsoft.com/en-us/previous-versions/windows/it-pro/windows-server-2003/cc781134(v=ws.10)?redirectedfrom=MSDN

**Comment by devttys0** [comment]
NTFS support has been merged into the master branch!

**Comment by shiren00** [comment]
Thank you very much!
