### ISSUE TITLE
Add support for APFS Fillesystem 

### ISSUE THREAD

**Issue by shiren00** [ReFirmLabs/binwalk#716]
We would appreciate it if anyone with additional materials or actual dump files related to this could share them :D
tsk_recover supports this.

- https://en.wikipedia.org/wiki/Apple_File_System
- https://developer.apple.com/support/downloads/Apple-File-System-Reference.pdf

**Comment by devttys0** [comment]
WIP: https://github.com/ReFirmLabs/binwalk/tree/apfs_support

**Comment by devttys0** [comment]
APFS support is functional and merged into the master branch.

Note that tsk_recover was not able to actually extract any of the APFS images that I created (using both Linux utilities and the OSX disk manager on a MacBook). The [latest version of 7zip](https://www.7-zip.org/a/7z2408-linux-x86.tar.xz) does work though, and has been added as a new external dependency.

**Comment by shiren00** [comment]
Thank you very much!!
