### ISSUE TITLE
Absence of processed data

### ISSUE THREAD

**Issue by Ricky-Tigg** [ReFirmLabs/binwalk#722]
Hello. Glad to witness in v. 3 to be released a transition to a memory-safe language.

v. 2.3.4 | Steps to reproduce; while being in Home directory:
```
$ sudo xz -dk /usr/lib/firmware/tlg2300_firmware.bin.xz
$ file -b /usr/lib/firmware/tlg2300_firmware.bin
data
$ binwalk -e /usr/lib/firmware/tlg2300_firmware.bin

DECIMAL       HEXADECIMAL     DESCRIPTION
--------------------------------------------------------------------------------

```
As per the output, there would be no data to deal with. If it is not an issue, that would imply that it must exist a case where that can be possible. However, with my current state of knowledge, so to say ignorance, that only seems to me unreasonable.

**Comment by shiren00** [comment]
Currently, Version 2 is being maintained here.
https://github.com/OSPG/binwalk

**Comment by devttys0** [comment]
The absence of any displayed results does not indicate that there was no data to analyze, but rather that there were no results found in the data that was analyzed. Perhaps the display of the column headers with no results underneath is confusing? The output from Binwalkv3 may be more clear:

```
$ binwalk tlg2300_firmware.bin 
Analyzed 1 file for 83 file signatures (185 magic patterns) in 2.0 milliseconds
```

Even though no results were displayed, Binwalkv3 reports that it did analyze the provided file. In general, not displaying results when there are no results to be displayed should be expected for most tools; for example, if you `grep` a file for some text that does not exist in that file, there will be no output from `grep`.

WRT the specific firmware image you're analyzing, I don't think there is anything that can be extracted (assuming I'm looking at the same firmware that  you are, I'm just going off the file name). It appears to just be raw ARM code and will need to be analyzed in a disassembler/decompiler:

```
$ cpu_rec tlg2300_firmware.bin 
Loading corpus from "/opt/cpu_rec/cpu_rec_corpus/*.corpus"
------------------------------------------------------------
        File         |     Range     | Detected Architecture
------------------------------------------------------------
tlg2300_firmware.bin | 0x0-0xc00     | ARMel                
tlg2300_firmware.bin | 0x4800-0x5800 | ARMhf                
tlg2300_firmware.bin | 0x7400-0x8000 | ARMhf                
tlg2300_firmware.bin | 0x9800-0xa800 | ARMhf                
tlg2300_firmware.bin | 0xac00-0xb800 | ARMhf                
------------------------------------------------------------
```
