### ISSUE TITLE
Missing --dd option in Rust rewrite

### ISSUE THREAD

**Issue by AnaJuliaCodes** [ReFirmLabs/binwalk#736]
The --dd option to extract everything to a directory shown in many online tutorials is now missing in the Rust rewrite.

**Comment by devttys0** [comment]
The `--dd` option in Binwalkv2 is now largely replaced with the `--carve` option in Binwalkv3. They are not exactly the same, but the `--carve` option in v3 does effectively the same thing that `--dd='*'` did in v2, namely, carve out all identified file types to their own separate files on disk.
