### ISSUE TITLE
Add update instructions when compiling from source

### ISSUE THREAD

**Issue by G-lacier** [ReFirmLabs/binwalk#744]
a set of instructions would be nice to have in the wiki on how to update and maintain updates if compiling from source.

**Comment by devttys0** [comment]
Thanks! I've added a note to the [Wiki page](https://github.com/ReFirmLabs/binwalk/wiki/Compile-From-Source) on this, but it's as simple as doing a `git pull` to get the latest code changes from the master branch and then re-building Binwalk with `cargo build --release`.
