### ISSUE TITLE
Build hangs on external domain query

### ISSUE THREAD

**Issue by osiris-plus** [ReFirmLabs/binwalk#764]
```
install -c -m 755 dmg2img vfdecrypt /usr/bin
--2024-11-25 09:43:34--  http://www.goffart.co.uk/s-record/download/srec_151_src.zip
Resolving www.goffart.co.uk (www.goffart.co.uk)... 85.233.160.142
Connecting to www.goffart.co.uk (www.goffart.co.uk)|85.233.160.142|:80... connected.
HTTP request sent, awaiting response...
```

Why are we downloading this from some random domain and what makes sure that this file is secure? Even worse, it's served over insecure HTTP.

**Comment by devttys0** [comment]
> Why are we downloading this from some random domain

That is the site where the `srec2bin` source code is hosted.

> what makes sure that this file is secure?

Not exactly sure what `secure` means in this context. I suppose it would have the same assurances as any piece of open source code downloaded from the internet.

> Even worse, it's served over insecure HTTP

D'oh, that's a problem! I'll update the install script to use https.

That said, I think that [srec_cat](https://manpages.ubuntu.com/manpages/focal/man1/srec_cat.1.html) looks like an appropriate substitute, and can be installed with `apt`.

**Comment by devttys0** [comment]
Removed source dependency on `srec2bin`, replaced with `srec_cat` (installed via `apt`).
