### ISSUE TITLE
Missing compress42 and tinfl libraries - OSX Mountain Lion

### ISSUE THREAD

**Issue by dovy** [ReFirmLabs/binwalk#77]
This issue pertains to the latest release, version 2.0.1.

I did:

```
./configure
make
sudo make install
```

I then attempt to run binwalk and receive the following:

```
WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

Signature Exception: Failed to locate libraries '['magic']'
```

The complete output is here (just callbacks): https://gist.github.com/dovy/9db56502b71554a3104c

Here's what's contained in my /usr/local/lib

![screen shot 2014-09-16 at 9 02 14 am](https://cloud.githubusercontent.com/assets/890963/4289321/89b5fc52-3db2-11e4-8eb6-fc30247cda02.png)

As you can see, we're missing `libtinfl.dylib` and `libcompress42.dylib`. I've tried to run the setup.py, but it doesn't seem to function on OSX. This also seems to be the same as issue #21, which was resolved a while ago.

Any ideas what I can do?  Thanks!

**Comment by kirkelifson** [comment]
`find / -name libcompress42.dylib` yields no results.

Yosemite 10.10.2, installed binwalk through Homebrew.

**Comment by jonbrenner** [comment]
@kirkelifson, @CyrilPeponne: As @runasand mentioned, the homebrew formula is borked and you need to manually build binwalk and use the libs from it. I hope to find some time to figure out brew packaging and fix it, but in the meantime you can use the libs that I built... if you trust me: https://gist.github.com/jonbrenner/d731d18e82c203dd1d81

**Comment by CyrilPeponnet** [comment]
Thanks for the head up, I will rebuild it from sources :P my mum always asks me to do not trust strangers :)

**Comment by devttys0** [comment]
Binwalk is now pure Python and no longer uses any C libraries, so this should be a non-issue for current builds. You should be able to just grab the latest code from the master branch and run `setup.py`.

**Comment by kirkelifson** [comment]
Cool, thanks!

**Comment by anddam** [comment]
@devttys0 can you push a release including the changes that fix this issue?

**Comment by PasF** [comment]
Mac OS x 10.10
@runasand :+1: thanks for your help
To fix "Exception: Failed to locate libraries '['magic']' "
<code>
sudo port install libmagic
</code>

The python installer failed to compile the lib, so just do:
<code>
./configure
make
sudo make install
sudo cp src/C/miniz/libtinfl.dylib /usr/local/lib/
sudo cp src/C/compress/libcompress42.dylib /usr/local/lib/
</code>

Then voilà !

**Comment by ethicalhack3r** [comment]
@runasand's solution worked for me too using binwalk 2.0.1 on Mac OS 10.10.5

**Comment by msmuenchen** [comment]
Macports' binwalk, version "binwalk @2.0.1 (cross)", still exhibits the error, sudo port install libmagic only helps against the exception.

**Comment by kenorb** [comment]
Or: `brew install libmagic xz` for OS X Homebrew environment.

**Comment by ThanosFisherman** [comment]
I still get this error on cygwin using binwalk 2.0.1 how can I install this libmagic you are talking about so I can fix this issue? I can't find it on cygwin
