### ISSUE TITLE
Feature Request: Support for Input via `stdin` and Output via `stdout`

### ISSUE THREAD

**Issue by johannesbremer** [ReFirmLabs/binwalk#783]
I’m using your tool in a somewhat unconventional way: I’m working on extracting my company's data out of an old proprietary WORM (Write Once Read Many) document storage system into an open-source solution. I wouldn’t have been able to do this without `binwalk`, because it's locating and extracting the content (and, by subtraction, also locating the metadata). Thank you for making this possible!

My issue is that `binwalk` doesn’t accept input via `stdin`. As a result, I’m forced to write to disk nearly half a million times instead of processing everything in-memory, which drastically slows down my pipeline.

I realize this use case might be somewhat niche, but I believe that supporting `stdin` for input and `stdout` for output could also benefit many regular users. For instance, it would streamline workflows involving Bash one-liners and other command-line pipelines.

Thank you again for this incredibly useful tool—not just for firmware reverse-engineering, but also for broader applications beyond the firmware space.

Cheers!

**Comment by devttys0** [comment]
Supporting `stdin` for analysis only (no extraction) shouldn't be too difficult, and I can definitely see other use cases for this.

Extraction would be a bit more difficult, for (as I see it) two reasons:

1. Binwalk relies on many external utilities to perform extraction which expect to be provided file paths as both their input and output; this would necessitate some wrapper code that writes data to disk, runs the extraction utility, then reads in the output file and sends it to `stdout`. This could work, but you'd still be doing a lot of disk I/O, so it doesn't seem that it would really solve your problem.
2. Sending the extracted data to `stdout` becomes complicated when there are multiple files to extract (for example, if you feed Binwalk some data that contains both `gzip` compressed data and `xz` compressed data), or when a more complex data type is extracted (e.g., a `SquashFS` file system or data archive which contains multiple files). The data printed to `stdout` in this case would need to be represented as JSON (or some similar format) describing all extracted files and their included content.

So, I suppose a little more detail on your use case would be helpful; are you mostly interested in identifying file signatures in some blob of data passed via `stdin`, or do you also need those file types to be extracted? Do you need recursive extraction?

**Comment by johannesbremer** [comment]
My bottleneck is mostly with `stdin` being missing. I mentioned `stdout` more for completeness. In my mind, I was picturing the extracted files as output, but from your explanation, I can see why that would be tricky to implement.

In my use case, I have an array of large blobs that include all kinds of data. Each entry in each blob is neatly separated by a header. I load each blob into memory, split it using the delimiter string, run `binwalk` on each entry to find where the header ends and extract the content (non-recursively), and grab some metadata from the header.

Everything before `binwalk` happens in memory, but because `binwalk` doesn’t accept `stdin`, I have to write each entry-blob to disk, run `binwalk` on it, and then delete it again. This extra I/O really slows things down.

If it helps, you can take a look at the script that handles part of the work [here](https://github.com/johannesbremer/worm-extractor/blob/main/worm2sql.nu).

**Comment by devttys0** [comment]
Got it! I should have some time to add `stdin` support over the weekend, I'll update this ticket when I do.

FYI, the latest mater branch currently has support for sending the JSON analysis results to `stdout` (specify a log file of `-`), so once `stdin` support is added you'll be able to pass your data to `stdin` and get the JSON results from `stdout`.

**Comment by johannesbremer** [comment]
That’s amazing—thank you so much! 

I appreciate the tip, and I can definitely use that feature in my script.

While I have your attention, I noticed the `--threads` flag. So far, I’ve just left it at the default, but would you recommend experimenting with it to squeeze out even more performance?

**Comment by devttys0** [comment]
The default thread count will be equal to the number of available CPU cores on your system.

Binwalk will only analyze one file per thread, so having more than one thread only makes a difference when performing a recursive extraction where there is more than one file to analyze.

When you _are_ performing recursive extraction, my experience is that adding more threads than available CPU cores doesn't really help much (and in fact, can actually slow down analysis time), since each thread will pretty much max out the CPU core at 100%. Trying to run, say, 100 threads that each want 100% of your CPU time on a system with only 8 CPU cores isn't very helpful. :)

On the other hand, reducing the number of threads during recursive extraction can be helpful if there are many very large files. Binwalk will read each file into memory in its entirety, so limiting the number of concurrent threads will reduce memory usage.

**Comment by johannesbremer** [comment]
That’s helpful, thanks! In that case, I’ll focus on other parts of my pipeline first.

**Comment by devttys0** [comment]
Support for reading from standard input via the `--stdin` argument has been merged into the master branch. You can now:

```
$ cat test.gz | binwalk --extract --stdin --quiet --log - 
[
{
  "Analysis": {
    "file_path": "/home/craig/Downloads/extractions/stdin",
    "file_map": [
      {
        "offset": 0,
        "id": "0e868d95-41e5-42d0-ac3a-d5f20b948dfc",
        "size": 108096828,
        "name": "gzip",
        "confidence": 250,
        "description": "gzip compressed data, operating system: Unix, timestamp: 1970-01-01 00:00:00, total size: 108096828 bytes",
        "always_display": false,
        "extraction_declined": false
      }
    ],
    "extractions": {
      "0e868d95-41e5-42d0-ac3a-d5f20b948dfc": {
        "size": 108096810,
        "success": true,
        "extractor": "gzip_built_in",
        "do_not_recurse": false,
        "output_directory": "/home/craig/Downloads/extractions/stdin.extracted/0"
      }
    }
  }
}
]
```

**Comment by johannesbremer** [comment]
Thank you again! I can’t believe you got it done within a day!
