### ISSUE TITLE
How to compile from source in windows ?

### ISSUE THREAD

**Issue by shiwanghua** [ReFirmLabs/binwalk#792]

**Comment by devttys0** [comment]
I haven't tried yet :)  I  expect it *should* compile, the only hang-up might be some of the non-Rust libraries that some of Binwalk's build dependencies require. Have you tried compiling it on Windows? Are you getting a specific error?

**Comment by Anonym271** [comment]
`cargo build --release` seems to be working for me on Windows 11

**Comment by devttys0** [comment]
I've made a note in the Wiki that building and running Binwalk on Windows should work, but is not officially tested.
