### ISSUE TITLE
Support for big endian detection in sqashfs (and possibly other signatures)

### ISSUE THREAD

**Issue by 1nikolas** [ReFirmLabs/binwalk#805]
It seems that unlike v2, v3 doesn't detect big endian Squashfs portions. I don't know if this applies to other signatures but I stumbled upon this example, I can send the firmware file if needed. Thanks

![Screenshot 2024-12-23 at 9 23 21 PM](https://github.com/user-attachments/assets/5ea5abe8-aac7-4a05-98b6-fd62bf89161f)
![image](https://github.com/user-attachments/assets/e9e0adcc-e4bd-4892-bc13-6f17689f5b0e)

(both screenshots are the same file)

**Comment by devttys0** [comment]
Big endian SquashFS is supported, so perhaps it is just this particular signature that isn't recognized. If you can provide the firmware file I can take a look at it.

**Comment by 1nikolas** [comment]
[101AZG0C0.bin.zip](https://github.com/user-attachments/files/18240683/101AZG0C0.bin.zip)

This is the file. I think this did not extract with unsquashfs I had to use the other one (sasquatch or how it's called).

**Comment by devttys0** [comment]
This was an issue with parsing version 2 of the SquashFS superblock structure, it has been fixed in the master branch:

![image](https://github.com/user-attachments/assets/485d4ae4-0c46-4f52-9abd-fe8fd764e6d4)
