### ISSUE TITLE
binwalk 3.3.1 extract zip failed  but unzip can extract succefully

### ISSUE THREAD

**Issue by beruhan** [ReFirmLabs/binwalk#807]
![image](https://github.com/user-attachments/assets/75c8e345-c29c-44f6-b153-e94831d56142)

**Comment by devttys0** [comment]
As the error message indicates, you are missing the `7zz` utility (7zip) which Binwalk uses to extract ZIP files. On Ubuntu/Debian this can be installed via `sudo apt install 7zip`; the package name may vary for other Linux distros.

FYI, you can always view which utilities Binwalk uses for extraction by running `binwalk --list`.
