### ISSUE TITLE
Failed to load plugin module

### ISSUE THREAD

**Issue by ghost** [ReFirmLabs/binwalk#81]
i have this in linux mint 17 32bit

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'

---

I tried re-installing binwalk, but the problem always appear

**Comment by cclamb** [comment]
Hi! Still a problem unfortunately.  Ubuntu 14.04 LTS server, libraries are not in /usr/local/lib/python2.7/dist-packages/binwalk/libs/ and python -O $(which binwalk) /bin/ls yields:

WARNING: Failed to load plugin module 'zlibvalid': Failed to locate libraries '['tinfl']'
DEBUG: Searching for '/usr/local/lib/python2.7/dist-packages/binwalk/libs/libcompress42.so'
DEBUG: Searching for '/usr/local/lib/libcompress42.so'
DEBUG: Could not find library 'compress42'

WARNING: Failed to load plugin module 'compressd': Failed to locate libraries '['compress42']'

and

DEBUG: Searching for '/usr/local/lib/python2.7/dist-packages/binwalk/libs/libtinfl.so'
DEBUG: Searching for '/usr/local/lib/libtinfl.so'
DEBUG: Could not find library 'tinfl'

The source is distributed, but as fair as I can tell, not built (e.g. src/C contains compress and miniz and associated C files).

I am using v. 2.0.1 downloaded a few days ago. Running make for miniz and compress both fail with file truncation errors too.  Any workarounds?

**Comment by cclamb** [comment]
Make output; seems like I need more context for this to work?

reverse@reverse:~/Downloads/binwalk-2.0.1/src/C$ make
make -C miniz
make[1]: Entering directory `/home/reverse/Downloads/binwalk-2.0.1/src/C/miniz'
cc  -shared -Wl,,libtinfl. tinfl.o -o libtinfl. 
/usr/bin/ld: cannot find : No such file or directory
libtinfl.: file not recognized: File truncated
collect2: error: ld returned 1 exit status
make[1]: *** [libtinfl.] Error 1
make[1]: Leaving directory `/home/reverse/Downloads/binwalk-2.0.1/src/C/miniz'
make: *** [all] Error 2

**Comment by cclamb** [comment]
yeah, I can add SOEXT as 'so' in my environment, then it fails with an unknown SONAME; not sure what that should be.  Seems like maybe this is no longer called by the primary build script.

**Comment by cclamb** [comment]
running "configure ; sudo make ; sudo make install" in the binwalk directory will build and install the needed libraries on ubuntu. Seems the python-based build and install process is not doing this right now. Nor is the dependency on C libraries removed it seems.
